### PR TITLE
Integrate AppTP with privacy remote config

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/72649045549333/1202005414608950/f

### Description
_NOTE: originally stacked PR onto #1830 -> #1829_ 

Integrates AppTP with privacy remote config

### Steps to test this PR

_Test internal builds_
- [x] fresh install from INTERNAL debug builds
- [x] launch the app
- [x] verify the `apptp_remote_config.db` contains a table dubbed `vpn_config_toggles`
- [x] verify the `vpn_config_toggles` table contains `ipv6Support`, `privateDnsSupport`, `networkSwitchHandling` and `badHealthMitigation` entries
- [x] verify all entries are false (`0`) for both `enabled` and `isManualOverride` columns except for `badHealthMitigation` that should have `enabled` set to true (`1`)
- [x] go to Settings -> AppTP dev settings
- [x] verify all toggles are disabled
- [x] go to Settings -> App Tracking Protection and enable AppTP
- [x] go to Settings -> AppTP dev settings
- [x] verify all toggles are in state enabled
- [x] verify only `VPN debug logging`, `Bad health monitoring` and `Bad health mitigation action` toggles are ON, remaining ones should be OFF
- [x] filter logcat by `Dropping ipv6`
- [x] open instagram and verify logs appear (dropping IPv6 packets) - you may need to in cellular if you don't see logs on WIFI
- [x] close instagram
- [x] go to Settings -> AppTP dev settings and toggle IPv6 support ON
- [x] open instagram and verify no logs appear
- [x] go to Settings -> AppTP dev settings and toggle IPv6 support OFF
- [x] filter logcat by `private dns`
- [x] go to Android settings and search for private DNS
- [x] set `Private DNS provider hostname` to `one.one.one.one`
- [x] verify `Private DNS support is disabled...skip` appear
- [x] set Private DNS to off
- [x] verify `Private DNS support is disabled...skip` appear
- [x] go to Settings -> AppTP dev settings and toggle `Private DNS support` ON
- [x] set `Private DNS provider hostname` to `one.one.one.one`
- [x] verify `Setting private DNS: ...` appear and VPN is restarted (look at the key icon in the status bar)
- [x] set Private DNS to off
- [x] verify `Setting private DNS: ...` DO NOT appear and VPN is restarted (look at the key icon in the status bar)
- [x] go to Settings -> AppTP dev settings and toggle `IPv6 Support` and `private DNS support` ON
- [x] In AS, open `privacy_config.json` file and set the `version` to `1648641758000` to force reload the remote settings on app launch
- [x] Filter logcat by `AppTpFeatureConfigImpl`
- [x] rebuild and install the app
- [x] launch the app
- [x] verify `Skip setEnabled...` appear for both `Ipv6Support` and `PrivateDnsSupport`
- [x] go to Settings -> AppTP dev settings
- [x] verify both IPv6 and privacy support toggles are still ON
- [x] verify opening instagram does not log any `Dropping ipv6...` message in logcat

_Test PLAY build_
- [x] Modify `AppTPHealthMonitor:simulateHealthStatusIfEnabled` method, so that the first `if` condition is `if (!appBuildConfig.isDebug)`
- [x] build and fresn install from PLAY debug build
- [x] Enable AppTp - grab invice code from [here](https://app.asana.com/0/0/1201184915504678/f)
- [x] Verify in logcat ipv6 packets are dropped when opening instagram
- [x] Verify in logcat `Private DNS support is disabled...skip` appears when trying to set private DNS from Android settings
- [x] Go to Settings -> App Tracking Protection screen -> overflo menu -> Diagnostics
= [ ] filter logcat by `AppBadHealthStateHandler`
- [x] scroll down and click on `BAD HEALTH` button
- [x] verify the `AppBadHealthStateHandler: Restarting the VPN....` message appears in logcat after a while
- [x] Click in `GOOD HEALTH` and wait for `no alerts` message
- [x] Click on `CRITICAL HEALTH`
- [x] verify that after a while `Restarting the VPN...` meessage appears and the diagnostics screen is killed (becauase we killed that process)

_Test app update_
- [ ] install from develop branch the INTERNAL build
- [ ] launch app and enable AppTP
- [ ] verify there is no `apptp_remote_config.db` database
- [ ] go to Settings -> AppTP settings
- [ ] verify `VPN debug logging` and `Bad health monitoring` and `Bad health mitigation` toggles are ON
- [ ] verify the rest of toggles are OFF
- [ ] click on `View diagnostics Data`
- [ ] scroll down and click on `CRITICAL HEALTH`
- [ ] verify the current activity is killed (it can take a while) - this is because the VPN process is restarted
- [ ] verify AppTP is enabled
- [ ] update the app from this branch (INTERNAL build)
- [ ] verify the `apptp_remote_config.db` exists and it has an EMPTY `vpn_config_toggles` table
- [ ] go to Settings -> AppTP settings
- [ ] verify `VPN debug logging` and `Bad health monitoring` and `Bad health mitigation` toggles are ON
- [ ] click on `View diagnostics Data`
- [ ] scroll down and click on `CRITICAL HEALTH`
- [ ] verify the current activity is killed (it can take a while) - this is because the VPN process is restarted
- [ ] verify AppTP is enabled
- [ ] go to Settings -> AppTP settings and enable `IPv6 support`
- [ ] verify the `vpn_config_toggles` db table contains the `ipv6Support` entry with `enabled` and `isManuallyOverride` columns set to `1`
- [ ] force kill the app and relaunch it
- [ ] go to Settings -> AppTP settings
- [ ] verify `ipv6 support` toggle is still ON
- [ ] verify the `vpn_config_toggles` db table contains the `ipv6Support` entry with `enabled` and `isManuallyOverride` columns set to `1`

_Test remote config updates_
- [ ] install from this branch the INTERNAL build
- [ ] open the app and enable AppTP
- [ ] go to Settings -> AppTP dev settings
- [ ] verify all toggles under `CONFIG` section are OFF
- [ ] verify the `vpn_config_toggles` table in the `apptp_remote_config.db` also has entries for all toggles (only badHealthMitigation` entry is enabled)
- [ ] use Charles to update the remote config file and update the ipv6 config to enabled and update the version
- [ ] kill and restart the app
- [ ] go to Settings -> AppTP dev settings
- [ ] verify the ipv6 toggle is ON
- [ ] verify the `vpn_config_toggles` table in the `apptp_remote_config.db` also has the ipv6 config as enabled and with `isManuallyOverride` set to `0`

### CODE REVIEW

**Comment by aitorvs** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #1829** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/1829" target="_blank">Graphite</a> 
    * **PR #1830** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/1830" target="_blank">Graphite</a> 
      * **PR #1832** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/1832" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/1832?utm_source=stack-comment).

**Review by marcosholgado — APPROVED** [review]
Everything working as expected 👍 🚢 🇮🇹

**Comment by aitorvs** [comment]
@marcosholgado after the last commit that added the support for default values, I have added to the description one more test case to run to ensure it works as expected.
I have run it and seems all good, lmk

**Comment by marcosholgado** [comment]
> @marcosholgado after the last commit that added the support for default values, I have added to the description one more test case to run to ensure it works as expected.
> I have run it and seems all good, lmk

LGTM!

**Pull request merged**
