### PR TITLE
Fix webview positioned partially offscreen (#638)

### PR DESCRIPTION
**Pull request by mattrob33**
Task/Issue URL: #638 
Tech Design URL: 
CC: @CDRussell 

**Description**:
After this change, bottom-anchored content in web pages will display anchored to the bottom of the screen, rather than being partially hidden offscreen.

**Steps to test this PR**:
1. Navigate to reddit.com or m.youtube.com

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by subsymbolic** [comment]
@CDRussell are you happy to grab this one? You're probably the best person to review it since you investigated this issue last time.

**Comment by CDRussell** [comment]
Thanks for answering the #help-wanted tag and for this contribution @mattrob33 !

I tested this out and it's certainly fixed the bottom issue, but it seems to have introduced unintended side effects:

1. Now the toolbar can be scrolled away, even if the `WebView` isn't scrolling. This can be seen on reddit.com when the bottom sheet / "use our app" component shows. If you try to scroll the screen, the toolbar moves around even though the web content is fixed. This isn't a major issue, and wouldn't itself be a blocker to including.
2. A bigger issue seems to be that now the top of the `WebView` content is being covered by the toolbar in some cases. I've attached a screengrab to illustrate the problem. That white youtube toolbar is hard to reach now as our native toolbar sits on top of it if you scroll to the top of the page. So to access that toolbar, you'd have to scroll all the way to top of the page, then try slowly scrolling down to hide our toolbar. 

I feel like your solution is much closer to what we need but still needs some tweaks yet. Do you have any thoughts on how to solve those issues?

can't-access-top-of-web-content

**Comment by mattrob33** [comment]
Ah yikes. I'll look into CoordinatorLayout a bit more for a better adjustment. Ideally the WebView would always top-align with the bottom of the omnibox and bottom-align with the bottom of the screen, right?

**Comment by CDRussell** [comment]
> Ideally the WebView would always top-align with the bottom of the omnibox and bottom-align with the bottom of the screen

I think top-aligning with the bottom of the omnibox, yes. Basically want to replicate how Chrome handles this as it does it well.

**Comment by sanogueralorenzo** [comment]
Hello 👋 

I was going to open an issue regarding this but I believe this PR is addressing it 🤔 

Tested on latest release + develop (that doesn't have the bottom bar anymore 😢 ) and have the same unexpected behavior
image

**Pull request closed without merging**
