### PR TITLE
Bookmark Folders

### PR DESCRIPTION
**Pull request by joshliebe**
Task/Issue URL: https://app.asana.com/0/72649045549333/1161200816074835/f
Tech Design URL: https://app.asana.com/0/481882893211075/1200496630620092/f
CC: 

**Description**:
This PR adds bookmark folder functionality.

**Steps to test this PR**:

- Freshly install the app.

> Add a folder

1. Go to "Bookmarks"
2. Tap the "add folder" action button to add a folder.
3. Verify that the "checkmark" action button isn't shown if there is no title.
4. Add a title.
5. Verify that the "checkmark" action button is shown.
6. Tap the "checkmark" action button.
7. Verify that a folder is created.
8. Verify that the folder's subtitle says "Empty".

> Add a subfolder

1. Tap on the newly created folder.
2. Tap the "add folder" action button and create subfolder/s.
3. Verify that the item count subtitle on the parent folder is correct.

> Edit a folder:

1. Edit one of the folders.
2. Verify that the "checkmark" action button isn't shown.
3. Delete the title.
4. Verify that the "checkmark" action button is not visible.
5. Push hardware back or the up arrow.
6. Verify that the folder title is not updated.
7. Edit the folder again.
8. Change the "location" of the folder.
9. Verify that the selected folder in the folder tree is correct.
10. Verify that the folder cannot be added to any of its subfolders.
11. Verify that the "checkmark" action button is shown.
12. Change the folder's title.
13. Tap the "checkmark" action button.
14. Verify that the folder's location and title have changed.

> Edit a bookmark (Browser):

1. Add a bookmark.
2. Click "Edit" on the SnackBar that is shown.
3. Verify that the "checkmark" action button is not shown.
4. Change the title, URL and location fields.
5. Verify that the "checkmark" action button behaves as expected.
6. Tap the "checkmark" action button.
7. Verify that the changes to the bookmark's title, URL and location are reflected.

> Edit a bookmark (Bookmarks list):

1. Add a bookmark.
2. Go to "Bookmarks".
3. Edit a bookmark in the list.
4. Verify that that the behavior is as expected.

> Edit a favorite (Browser):

1. Add a favorite.
2. Click "Edit" on the SnackBar that is shown.
3. Verify that the "checkmark" action button is not shown.
4. Change the title and URL.
5. Verify that the "checkmark" action button behaves as expected.
6. Tap the "checkmark" action button.
7. Verify that the changes to the favorite's title and URL are reflected.

> Edit a favorite (Favorites list):

1. Add a favorite.
2. Go to "Bookmarks".
3. Edit a favorite in the list.
4. Verify that that the behavior is as expected.

> Deletion (Empty folder):

1. Delete an empty folder.
2. Verify that the folder is immediately deleted.
3. Tap the "Undo" action in the SnackBar that is shown.
4. Verify that the folder re-added.

> Deletion (Non-empty folder):

1. Delete a folder with subfolders and bookmarks.
2. Verify that a dialog is shown with the correct folder title and item count.
3. Tap "Cancel".
4. Verify that the folder is not deleted.
5. Delete the folder again and tap "Delete" on the dialog.
6. Verify that the folder is deleted.
7. Tap the "Undo" action in the SnackBar that is shown.
8. Verify that the folder (And its contents) are re-added.

> Search:

1. Verify that the "search" action button is not shown if there are no bookmarks or folders.
2. Add some bookmarks and folders.
3. Verify that the "search" action button is shown.
4. Tap the "search" action button.
5. Verify that all of the bookmarks and folders are shown in the list.
6. Verify that the folders have the correct item counts.
7. Tap a folder.
8. Verify that the folder is navigated to successfully.
9. Verify that the opened folder has the "search" action button even if it is empty.
10. Tap the search button.
11. Tap a bookmark.
12. Verify that the bookmark opens successfully.

> Import/export:

1. Add some bookmarks and create some folders (Make sure to add some subfolders with bookmarks).
2. Export the bookmarks using the overflow menu.
3. Check that the confirmation SnackBar is shown.
4. Delete all bookmarks and folders.
4. Import the bookmarks back into DuckDuckGo.
5. Verify that the bookmarks and folder structure were imported correctly.
6. Importing the same file twice, should import the same folders twice.

> Import/export from external:

1. Open the folder at this location: [app/src/androidTest/resources/bookmarks/](https://github.com/duckduckgo/Android/tree/feature/josh/bookmark-folders/app/src/androidTest/resources/bookmarks).
2. Copy these files onto a test device/emulator.
3. Import each of these files into DuckDuckGo.
4. Verify that these files import correctly into DuckDuckGo except for [bookmarks_invalid.html](https://github.com/duckduckgo/Android/blob/feature/josh/bookmark-folders/app/src/androidTest/resources/bookmarks/bookmarks_invalid.html).

> Test migration:

1. Switch to develop and install the app.
2. Switch to [feature/josh/bookmark-folders](https://github.com/duckduckgo/Android/tree/feature/josh/bookmark-folders) and install the app.
3. Verify that the app upgrades successfully and opens as expected.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by D19A66B55** [comment]
When editing /scrolling bookmarks, app keeps closing.
Also->
To be able to organize bookmarks..A-Z etc. & to create folders within bookmarks.

**Comment by D19A66B55** [comment]
Hi Josh, 
I just want to thank you for your time & efforts on this project, especially the bookmarks.
I am totally looking forward to the implementations to Dax.

**Comment by joshliebe** [comment]
@malmstein  I've made all the requested changes, please re-check 🙂

**Review by malmstein — APPROVED** [review]
This looks great @joshliebe. Thanks a lot, great job!

**Comment by D19A66B55** [comment]
Hi Josh-
B4 I start, I do want to thank you & malmstein for the work you've done.
Let me be clear, I don't exactly know what you're doing now to improve bookmarks but adding folders is o.k. but, there's no way to move the already created bookmarks into the folder.
When adding a folder, it's created in the Bookmarks section at the top but, the bookmarks that are already created can't be moved into the folder. 
I don't see that there's a way to Add a folder in Favorites because if there was a way & since the bookmarks in Favorites are the only ones that can be moved around within Favorites then there might have been hope of moving these marks into folders.
So, to be able to Move marks here to there, in & out of folders  is needed please. 
When marks are created, if they'd jump in alphabetical/numerical order, that would be awesome.
Just for example...I use to use FF
browser long ago & the bookmarks setup was terrific after a few updates that is. It had everything one could wish for in bookmarks. I'm talking about maybe the year 2017 or so.
DDG is no stranger to me & I'm not giving up the battle. 
I realize this is not your only project.
Hope I didn't bore you to tears...
Have a great day!

**Comment by joshliebe** [comment]
Hey @D19A66B55!

If you tap the three dots next to a bookmark and go to "Edit", there is now an additional field "Location" under the title and URL. If you tap "Location", you can specify which folder you'd like to move the bookmark to. Hope that helps!

Adding favorites to folders/ordering is currently not implemented, but thanks for the suggestions 👍

**Comment by D19A66B55** [comment]
Users need to know about the implementations & how to use them since you've worked so hard coding.
Actually, I really think Favorites is not needed. 
Just stick with "Bookmarks" & implement accordingly.
I realize DDG's main function is Search & that's beautifully done but, BM's are also important.
This is a good start & well done now that I know how.
Please keep adding functions when you get a minute or two.
Thanks & have a nice day😊







created b4 new function implemented....there's no "Location" listed.
2nd>I created new folder & then created a new mark.
3rd>I tapped 3 dots>"Edit">"Location" & there was only blankness with the exception of

**Comment by D19A66B55** [comment]
Hi Josh,
Here's the probs...
(1) When saving or moving bookmarks to different folders, every once in a great while they'll align alphabetically or numerically. Aligning all the time is whats going to make life easier.
(2) Favorites and Adding bookmarks never align.
(3) When clicking on Edit a folder or file, the location can't be seen.
I apologize for adding to your heavy workload but, if the above is corrected, I'm sure I won't be the only happy camper🙂
Thanks for your time, efforts and hard work.
Have a great day!

**Comment by joshliebe** [comment]
Hi @D19A66B55, 

Regarding (1) and (2), we currently don't support ordering of bookmarks. Please log a feature request if you believe this functionality should be added.

Regarding (3), please log a bug for this with screenshots and reproducible steps.

Bugs and feature requests can be added here: https://github.com/duckduckgo/Android/issues.

Thanks!

**Comment by D19A66B55** [comment]
Josh,
As we're all thankful for the work you do, the fact is that you and others are working on this project and bookmarks ARE part of the project.
Why wouldn't you want to make improvements on them especially when it's beneficial?
Your sorry excuse for ignoring this issue is disappointing.
When you take on a project, you take on the WHOLE project. If you don't want to work on a specific part of the project, assign it to someone else but, please don't blow me off with your excuses.
I'm just disappointed in your attitude but I do wish you well in your future endeavors.

**Pull request merged**
