### PR TITLE
Native crash handling

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/488551667048375/1207205378744694/f

### Description
Add native crash handler and basic reporting

### Steps to test this PR

_Test native crash handing_
- [ ] apply the patch from [this Asana task](https://app.asana.com/0/0/1207245766479035/f) to this PR
- [ ] build and install and launch app
- [ ] verify `Native crash handler init pixel sent` appears in logcat
- [ ] verify `Native crash handler successfully initialized.` apperas in logcat
- [ ] verify app crashes and `Native crash pixel sent` appears in logcat
- [ ] In kibana, verify pixels appear when applying this filter `pixel:m.app*.native.crash.*`
- [ ] pixels have the right params, `main` process name, right `appVersion` and right `customTab` true/false value

### CODE REVIEW

**Comment by aitorvs** [comment]
* **#4517** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4517?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @aitorvs and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by CDRussell** [comment]
Tried testing with the patch; it crashes but i'm not seeing any pixels (not in logcat nor kibana). Will wait until we get a chance to pair to look more into it as I might be doing something wrong in the testing, but heads up in case you know why this might be the case, @aitorvs

**Comment by aitorvs** [comment]
> Tried testing with the patch; it crashes but i'm not seeing any pixels (not in logcat nor kibana). Will wait until we get a chance to pair to look more into it as I might be doing something wrong in the testing, but heads up in case you know why this might be the case, @aitorvs

We can take a look tomorrow. I used the patches and could crash and see the pixels in kibana.
Admittedly the test steps were not very accurate (fixed that) so maybe that was the issue.

Gonna run this on emulator as well to see if there's any difference (been running it in pixel 4XL)

**Review by CDRussell — APPROVED** [review]
Still unsure about custom tab param (see comment), but otherwise, LGTM

**Pull request merged**
