### PR TITLE
AppTP: Remove prepopulation of AppTrackerEntity

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: 
https://app.asana.com/0/488551667048375/1201722332762154/f

### Description
Remove the prepopulation method as we no longer need it.

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3443** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3443" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3443?utm_source=stack-comment).

**Comment by malmstein** [comment]
@karlenDimla can I assign this to you since @aitorvs  is out?

**Review by karlenDimla — COMMENTED** [review]
LGTM
- I don’t have full context on why we want to remove this. But following convos on the attached task, this is only relevant to very old version which now has very low AppTP DAUs.

**Comment by malmstein** [comment]
Thanks @karlenDimla !

**Pull request merged**
