### PR TITLE
fix: convert clip data into plain text before pasting to omnibar

### PR DESCRIPTION
**Pull request by hotchemi**
Task/Issue URL: https://github.com/duckduckgo/Android/issues/1074

**Description**:

- This PR modifies `KeyboardAwareEditText` to be aware of pasting text from the clipboard and clear its style beforehand.
  - If API level >= M, we can just use [R.id.pasteAsPlainText](https://developer.android.com/reference/android/R.id#pasteAsPlainText)
  - If API level < M, we need to manually clear and set the data to primary clip again(see `ClipboardManager.convertClipToPlainText`)

#### Discussion

- Now `KeyboardAwareEditText` has kind of two responsibilities and I was thinking I should rename the class as `OmniToolbarEditText` or something, but since this is my 1st PR as an external contributor I'd like to keep the diff smaller as much as I can. Let me know your thoughts around here🙏

**Steps to test this PR**:

1. API level >= M
  - Launch the emulator with API Level M
  - Open https://www.theverge.com/2018/1/23/16922508/private-search-engine-duckduckgo-browser-extension-app
  - Copy bold "DuckDuckGo" from the title
  - Paste the clipboard clip to omnibar search input area
  - Confirm there's no rich text formatting
 
2. API level < M
  - Launch the emulator with API Level M
  - Open https://www.theverge.com/2018/1/23/16922508/private-search-engine-duckduckgo-browser-extension-app
  - Copy bold "DuckDuckGo" from the title
  - Paste the clipboard clip to omnibar search input area
  - Confirm there's no rich text formatting

##### API level >= M

| Before |  After |
:-------------------------:|:-------------------------:
|

##### API level < M

| Before |  After |
:-------------------------:|:-------------------------:
|
---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by cmonfortep** [comment]
Thanks, we will take a look as soon as possible.

**Review by malmstein — CHANGES_REQUESTED** [review]
Thanks for the submission @hotchemi. This is indeed very helpful and fixes an issue, good job!

On the actual code:
1. How do you feel about not using extension functions? We don't really need this feature anywhere else and I'd prefer if the `convertClipToPlainText` function would only be known to the `KeyboardEditText`
2. On the naming of the `EditText` itself, we are working on a few things internally that will change its behavior, so it's better not to change anything else just yet.

**Comment by hotchemi** [comment]
@malmstein Thank you for the quick review!

- RE: 1 I'm fine with your suggestion and let me make my aim clear just in case🙏 My intention here for using Kotlin's extension function is to provide a more readable way to define logic and actually those extensions are not available outside of `KeyboardAwareEditText`(because those are private, which I've occasionally seen in Kotlin [repo](https://github.com/JetBrains/kotlin/blob/cc51869a2abb590b7c830cece7a6bec94901fdfa/plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/annotationProcessing.kt#L222-L234))🙇 

- RE: 2 Roger that!

**Comment by malmstein** [comment]
@hotchemi thanks for clarifying, I completely missed the `private` on the extension functions declaration! It actually reads quite nice and I'm happy with it.

Thanks for the contribution!

**Review by malmstein — APPROVED** [review]
Happy with the changes because the extension functions are private to the `View`
:shipit:

**Comment by hotchemi** [comment]
Thank you so much for your review😄🙏

**Pull request merged**
