### PR TITLE
ADS: Lint Rules

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/1174433894299346/1203399378949473

### Description
Set of Lint rules to help develop using the new Android Design System:
- Listed under https://app.asana.com/0/1174433894299346/1203399378949473

Loads of unused resources and attributes have been removed.
The baseline files have been updated to match the new rules.

### Steps to test this PR
Run .`/gradleW lint`

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2668** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2668" target="_blank">Graphite</a> 
    * **PR #2697** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2697" target="_blank">Graphite</a>  👈
    * **PR #2682** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2682" target="_blank">Graphite</a> 
    * **PR #2678** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2678" target="_blank">Graphite</a> 
    * **PR #2677** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2677" target="_blank">Graphite</a> 
    * **PR #2687** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2687" target="_blank">Graphite</a> 
    * **PR #2666** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2666" target="_blank">Graphite</a> 
      * **PR #2667** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2667" target="_blank">Graphite</a> 
      * **PR #2671** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2671" target="_blank">Graphite</a> 
    * **PR #2674** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2674" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2697?utm_source=stack-comment).

**Comment by nalcalag** [comment]
Lint is failing locally

Screenshot 2023-01-30 at 10 52 09

**Review by nalcalag — CHANGES_REQUESTED** [review]
Lint is failing locally
Screenshot 2023-01-30 at 10 52 09

**Review by nalcalag — APPROVED** [review]
LGTM! 💯

**Pull request merged**
