### PR TITLE
It translation improvement

### PR DESCRIPTION
**Pull request by Zoo-M0**
Task/Issue URL: https://github.com/duckduckgo/Android/issues/559

### Description
Fixed/improved some it strings

### Steps to test this PR
Should not need tests

### CODE REVIEW

**Review by MattV27 — APPROVED** [review]
I agree with you. A question like this needs the verb in the infinite form.

**Comment by Zoo-M0** [comment]
Hi guys, can I have an update on this? Let me know if there is something to change

**Comment by cmonfortep** [comment]
Thanks @Zoo-M0 

As per our [translations guidelines](https://github.com/duckduckgo/Android/blob/de velop/TRANSLATIONS.md#improve-language-translations): "We only accept translations tweaks that fix actual issues (typos, grammatical errors) and won't accept minor changes that are only focused on tweaking the wording"

Could you briefly explain if that's the case for this PR?

**Comment by Zoo-M0** [comment]
Sure, from my point of view there are some grammatical issues with word genres and single/plural forms, maybe the commit on emailSignOutDialogTitle could be considered a wording tweaking, but personally I consider it a grammatical issue.

**Comment by malmstein** [comment]
@cmonfortep do you have time to look at this or do you want to assign a new reviewer?

**Comment by Zoo-M0** [comment]
@cmonfortep any news on that? If it needs some more work I could look into it

**Comment by cmonfortep** [comment]
@Zoo-M0 I will take a look soon. Thanks.

**Comment by cmonfortep** [comment]
Thanks @Zoo-M0. PR is still on draft, is this ready for review? Otherwise, I took a look and I'm ok with the changes.

**Comment by Zoo-M0** [comment]
@cmonfortep sorry for leaving this in draft, I have updated the title but it appears to me still in draft, if it's ok to you merge it. I'm done.

I will search for issues where I can be helpful :)

**Review by cmonfortep — APPROVED** [review]

**Pull request merged**
