### PR TITLE
Change autofill subfeature names in prep for releasing

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/0/1204370666975082/f

### Description
Renames the autofill subfeatures, as is required to prepare for the autofill release.

### Steps to test this PR

**Start with develop branch.**
- [x] Checkout `develop`
- [x] Build using `play` variant, and do a clean install. 
- [x] Give the app a few seconds after launching to fetch the remote config.
- [x] Verify that autofill is NOT visible (e.g., you cannot access the credential management screen)

**Use new remote config**
Change URL we use for the remote config (it's defined in `PrivacyFeatureName.PRIVACY_REMOTE_CONFIG_URL`)
- [x] change it to https://jsonblob.com/api/1095045267291652096 
- [x] Make the above change to the URL in `develop`
- [x] Build using`play` variant again, and install the app. 
- [x] Give the app a few seconds after launching to fetch the remote config.
- [x] Verify that autofill is still NOT visible (e.g., you cannot access the credential management screen)

**Checkout the branch from this PR**
- [x] Checkout the branch from this PR, and apply the URL change as above so it's getting the new remote config type
- [x] Install using `play` variant again.
- [x] Give the app a few seconds after launching to fetch the remote config.
- [x] Verify that autofill IS visible (e.g., you can access the credential management screen - you might need to launch a new tab to see it picked up in the overflow if you were already viewing a tab)
- [x] Verify that autofill is DISABLED by default ⚠️

### CODE REVIEW

**Comment by CDRussell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3053** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3053" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3053?utm_source=stack-comment).

**Review by marcosholgado — APPROVED** [review]
LGTM!

**Comment by CDRussell** [comment]
@marcosholgado, as discussed, pushed new commits to workaround the issue of autofill remote config block not being processed. re-review plz 🙏

**Review by marcosholgado — APPROVED** [review]
Re-test including the edge case that we found. All working as expected 👍

**Pull request merged**
