### PR TITLE
New header design: icons, app colors and edit text mode

### PR DESCRIPTION
**Pull request by subsymbolic**
Task/Issue URL: 
Update icons: https://app.asana.com/0/72649045549333/608322930507367
Update color pallette: https://app.asana.com/0/72649045549333/608322930507366
Add editing design to edit text: https://app.asana.com/0/72649045549333/613439415394753 

Tech Design URL: N/A

**Description**:
Adds new header design

**Steps to test this PR**:
Run the app and check that
• The icons and colors are updated
• Tabs icon is on main page
• The edit text mode hides other icons and shows new background when in edit mode

NOTE: There is a separate task to add a "count" to the tabs button.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by CDRussell** [comment]
@subsymbolic can you clarify, is "not" a typo here, or is the tab button not supposed to appear yet?

>Tabs icon is not on main page

**Comment by subsymbolic** [comment]
That is indeed a typo, thanks. Fixed!

**Comment by CDRussell** [comment]
Testing on smaller device makes the toolbar behave unexpectedly.

`400x800` Nexus S emulator [hdpi]

screen shot 2018-04-05 at 11 35 24
screen shot 2018-04-05 at 11 35 29

**Comment by CDRussell** [comment]
__Unused resources__
- In `styles.xml`, I don't think we need `TransparentToolbar` any more as a result of your changes.
- In `strings.xml`, I don't think we need `R.string.privacyDashboard` any longer

**Comment by subsymbolic** [comment]
@CDRussell & I chatted about the overflow behavior on small devices. We have decided to "force show" those buttons rather than allowing them to overflow. We tested this on a number of devices and in split screen mode and it looks good.

**Pull request merged**
