### PR TITLE
Launch BrowserActivity when tapping on dax logo (widget)

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/488551667048375/1201659732216532/f 

### Description
Open app from the widget when tapping on dax logo

### Steps to test this PR

_Tap on dax icon opens app_
- [x] Add both favorites and search widgets to home screen
- [x] Tap on the dax icon on the widget
- [x] Check browser is open

_Tap on search bar opens interstitial scrren_
- [x] Add both favorites and search widgets to home screen
- [x] Tap on the search bar on the widget
- [x] Check interstitial screen is open

_Empty favorites (regression)_
- [x] Clear app data
- [x] Add favorites widget to home screen
- [x] Tap on add favorites on the widget
- [x] Check app is open and instructions to add favorites are displayed

_Non-empty favorites (regression)_
- [x] Add a favorite site
- [x] Add favorites widget to home screen
- [ ] Tap on a favorite on the widget
- [ ] Check app is open and selected site is loaded

### UI changes
No UI changes

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3634** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3634" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3634?utm_source=stack-comment).

**Comment by joshliebe** [comment]
@CrisBarreiro It looks good but when I tap the sites on the widget it's opening an empty tab:
https://github.com/duckduckgo/Android/assets/3471025/fc13cf61-4c86-4f17-b3f0-8f1668b55ae3

The test device is a Pixel 7 Pro (Android 13).

**Comment by CrisBarreiro** [comment]
> @CrisBarreiro It looks good but when I tap the sites on the widget it's opening an empty tab: https://github.com/duckduckgo/Android/assets/3471025/fc13cf61-4c86-4f17-b3f0-8f1668b55ae3
> 
> The test device is a Pixel 7 Pro (Android 13).

@joshliebe I reverted the changes to the favorite grid click listener and it seems to be working fine for me. Could you please have another look?

**Comment by CrisBarreiro** [comment]
> @CrisBarreiro, @joshliebe what's the state of this PR?

@marcosholgado need to further investigate some issues when updating the app, closing it for now

**Pull request closed without merging**
