### PR TITLE
Replaced dialog box with snackbar in Bookmarks+fireproof websites

### PR DESCRIPTION
**Pull request by anoopaneesh**
Addressing issue: #945 

I have a added a snackbar when user deletes a bookmark or fireproof website.The snackbar contains a undo option which can be used to cancel the deletion.I have used string resources instead of hardcoded string .
Screenshot_1601553190
Screenshot_1601552863

### CODE REVIEW

**Comment by cmonfortep** [comment]
@anoopaneesh Thanks for the contribution! 

This is failing because our ktlint detected some codestyle issues:

```
/bitrise/src/app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt:143:61: Missing spacing before "{"
/bitrise/src/app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt:34:1: Unused import
/bitrise/src/app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt:108:41: Missing spacing before "{"
/bitrise/src/app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesActivity.kt:30:1: Unused import
/bitrise/src/app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesActivity.kt:83:61: Missing spacing before "{"
/bitrise/src/app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesViewModel.kt:75:64: Missing spacing before "{"
/bitrise/src/app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesViewModel.kt:77:55: Missing spacing before "{"
```

You can fix them manually, or[ configure your Android studio with our setup](https://github.com/duckduckgo/Android/blob/develop/styleguide/STYLEGUIDE.md#android-studio-setup).

**Comment by malmstein** [comment]
Thanks for the contribution @anoopaneesh! I'll take a look at the implementation during this week.

**Review by malmstein — CHANGES_REQUESTED** [review]
Thanks for the contribution @anoopaneesh, a few comments before I do some manual testing:

- Can you add tests for the new methods added to the `ViewModel`?
- This project is translated to several languages, but you have only changed the text for English. Can you add two new entries to `strings-untranslated` with the new snackbars messages? Also remove the old `bookmarkDeleteConfirmMessage` and `fireproofWebsiteDeleteConfirmMessage` from all the other string files.

**Comment by anoopaneesh** [comment]
added two new entries to strings-untranslated with the new snackbars messages. Also removed the old bookmarkDeleteConfirmMessage and fireproofWebsiteDeleteConfirmMessage from all the other string files.

**Review by malmstein — CHANGES_REQUESTED** [review]
Thanks for updating the strings @anoopaneesh, once the tests are added to the `ViewModel` we can close this one.

**Comment by cmonfortep** [comment]
@anoopaneesh Do you have plans to address the comments in this PR? Thanks.

**Comment by anoopaneesh** [comment]
I am really sorry that i couldnt work on these. I am not good at testing

**Comment by malmstein** [comment]
I've created https://github.com/duckduckgo/Android/pull/1056 to add the missing tests and fix the conflicts shown here

**Pull request closed without merging**
