### PR TITLE
Re-use shared onboarding flow across all release tests

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234542811812/f

### Description
Refactors release tests to make use of the shared onboarding flow, removing the need to duplicate those steps inside every individual test.

Other test types will be done in separate PRs.

### Steps to test this PR

- [ ] Verify e2e tests run successfully: https://github.com/duckduckgo/Android/actions/runs/5833949096

### CODE REVIEW

**Comment by marcosholgado** [comment]
This could also be added the maestro privacy tests right?

**Comment by CDRussell** [comment]
> This could also be added the maestro privacy tests right? The title says that but there are no privacy tests?

Sorry, this is for refactoring release tests ones. Renamed the PR. The other test types will be done in separate PRs and are captured as sub-tasks in [Restructuring Maestro tests for better reusability](https://app.asana.com/0/1202552961248957/1205234542811809/f)

**Comment by marcosholgado** [comment]
> 

While we are at it, why not doing it on this PR and change it everywhere?

**Comment by aitorvs** [comment]
> > Sorry, this is for refactoring release tests ones. Renamed the PR. The other test types will be done in separate PRs and are captured as sub-tasks in [Restructuring Maestro tests for better reusability](https://app.asana.com/0/1202552961248957/1205234542811809/f)
> 
> While we are at it, why not doing it on this PR and change it everywhere?

+1 seems like a very low effort to do that in this PR rather than N follow up PRs

**Comment by aitorvs** [comment]
> > > Sorry, this is for refactoring release tests ones. Renamed the PR. The other test types will be done in separate PRs and are captured as sub-tasks in [Restructuring Maestro tests for better reusability](https://app.asana.com/0/1202552961248957/1205234542811809/f)
> > 
> > 
> > While we are at it, why not doing it on this PR and change it everywhere?
> 
> To make incremental quicker improvements instead of delaying making any improvement until more work is done. Since this isn't a top priority work, I'd favor shipping improvements when they are available. Making this PR fix all tests increases the chance of it going stale while waiting to get the time to fix the other tests.

I am not sure I understand the logic for this "incremental change" when we're talking about 10-20min work to get it all done (we're probably incurring in more busy work, ie. process, opening multiple PRs for this than doing it all in just one PR).
But I am fine if you feel strongly about not doing it.

**Review by aitorvs — APPROVED** [review]

**Pull request merged**
