### PR TITLE
Rename whitelist to allowlist

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/488551667048375/1205221243351454/f

### Description
Rename whitelist to allowlist

### Steps to test this PR
* Install an older version of the app
* Add a site to the list of unprotected ones
* Install this one
* Check app starts normally and the unprotected sites list is unchanged

### UI changes
No UI changes

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3424** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3424" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3424?utm_source=stack-comment).

**Review by marcosholgado — APPROVED** [review]
LGTM!

To close the loop, can you create a task to rename the `user_whitelist` table to `user_allowlist`?

**Comment by CrisBarreiro** [comment]
> `user_whitelist`

Do you mean the database table?

**Comment by marcosholgado** [comment]
> > `user_whitelist`
> 
> @marcosholgado Do you mean the database table?

Yup

**Pull request merged**
