### PR TITLE
Register in VPN process as well

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/488551667048375/1207294405155930

### Description
Add native crash handling for VPN process now that we also have it for the main process

### Steps to test this PR
_Test native crash handing_
- [x] apply the patch from [this Asana task](https://app.asana.com/0/0/1207294405155932/f) to this PR
- [x] build and fresh install and launch app
- [x] Enable AppTP
- [x] verify `Native crash handler init pixel sent on vpn` appears in logcat
- [x] verify `Native crash handler successfully initialized on vpn.` apperas in logcat
- [x] verify VPN crashes and `Native crash pixel sent on vpn` appears in logcat
- [ ] In kibana, verify pixels appear when applying this filter `pixel:m.app*.native.crash.*`
_(pixels should have `pn=vpn` and the right version, may be difficult to find them as now we send for `pn=main` in production. Logcats above should be enough)_
- [ ] pixels have the right params, `vpn` process name, right `appVersion` and right `customTab` true/false value

_Test disabling crash handling_
- [x] use jsonblob or something else to set custom privacy config
- [x] add the following feature and set `nativeCrashHandlingSecondaryProcess` to `disabled`
```json
    "androidNativeCrash": {
      "exceptions": [],
      "state": "enabled",
      "hash": "38",
      "features": {
        "nativeCrashHandlingSecondaryProcess": {
          "state": "enabled"
        }
      }
    }
```
- [x] kill the processes and re-launch the app and verify none of the `vpn` related logcats in previous test appear

### CODE REVIEW

**Comment by aitorvs** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4519?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4519** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4519?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4517** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4517?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @aitorvs and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by CDRussell — APPROVED** [review]
> verify app crashes and Native crash pixel sent appears in logcat

Verifying expectations on this... i do see the pixel however the app doesn't crash. Instead, the VPN process dies; I assume this is what is expected and the testing step is wrong.

What i'm not sure about is how the reporting and retry mechanism go together; I see the VPN continually turn off and on again and native crash pixels fire over and over. Obviously it's crashing here because of the patch, but if it were a real crash are you worried about sending the same crash pixel repeatedly if it tries and fails to establish the VPN connection? I saw > 30 pixels generated before I realised what was happening.

Approving the PR on the assumption the above is all in line with your expectations on how that should work; let me know if not.

**Comment by aitorvs** [comment]
> Verifying expectations on this... i do see the pixel however the app doesn't crash. Instead, the VPN process dies; I assume this is what is expected and the testing step is wrong.
Yeah, copy/paste error, fixed.

> What i'm not sure about is how the reporting and retry mechanism go together; I see the VPN continually turn off and on again and native crash pixels fire over and over. Obviously it's crashing here because of the patch, but if it were a real crash are you worried about sending the same crash pixel repeatedly if it tries and fails to establish the VPN connection? I saw > 30 pixels generated before I realised what was happening.
> Approving the PR on the assumption the above is all in line with your expectations on how that should work; let me know if not.
Yeah, the VPN coming back right after a crash is a "feature" of the VPN. We bind to the process and try to recreate it if it crashes for unexpected reasons.
The addition here is the pixel we'll send. Granted it can end up in spikes, tbh I don't know how often that (vpn crash loop) happens in production

Maybe I add a different kill switch for VPN process registration in case we need to disable due to spamming pixels?

**Comment by CDRussell** [comment]
>Maybe I add a different kill switch for VPN process registration in case we need to disable due to spamming pixels?

@aitorvs good idea

**Review by joshliebe — APPROVED** [review]
Didn’t see any `pn=vpn` pixels in Kibana but otherwise works as expected 👍

**Pull request merged**
