### PR TITLE
Update About version

### PR DESCRIPTION
**Pull request by joshliebe**
Task/Issue URL: https://app.asana.com/0/488551667048375/1206765310240126/f

### Description
Cleans up the version on the “About” screen.

### Steps to test this PR
- [x] Go to Settings > About.
- [x] Verify that only the version and version code are displayed.

### CODE REVIEW

**Comment by joshliebe** [comment]
* **#4249** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4249?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @joshliebe and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by nalcalag — APPROVED** [review]
LGTM! 🔥

**Comment by marcosholgado** [comment]
It would be great to have the variant for internal users / debug builds

**Comment by nalcalag** [comment]
@marcosholgado we agreed on the Android Weekly Meeting last week that we should remove the variant at all for all build variants.
cc @aitorvs

**Comment by joshliebe** [comment]
> It would be great to have the variant for internal users / debug builds

I’m going to merge as is. If we miss it at a later date, we can add it back for internal only.

**Pull request merged**
