### PR TITLE
Handling target=_blank if link points to a file

### PR DESCRIPTION
**Pull request by AndrewR8**
Issue URL:  #753

**Steps to test this PR**:
1. Navigate to http://www.granditaliaperth.co.uk/menus.html and click on the download link for the menu.
1. The download will start and a new blank tab closes immediately

### CODE REVIEW

**Comment by subsymbolic** [comment]
Many thanks for submitting this, we really appreciate it. Unfortunately an earlier PR https://github.com/duckduckgo/Android/pull/663 has now been merged and clashes with your approach. If you get up to speed with the develop branch you'll see that closing the extra tab also dismisses the new download confirmation dialog.

If you want to try implementing a different solution, you are most welcome to update this PR. If not, that's ok too, just close this PR.

**Comment by AndrewR8** [comment]
`DownloadConfirmationFragment` is attached to `BrowserTabFragment`. It looks like there are only two available solutions :

1.  Attach `DownloadConfirmationFragment` to `Activity` (If empty tab should be closed) 

2. Empty tab will be open until user dismisses `DownloadConfirmationFragment`

I need your advice.

**Comment by subsymbolic** [comment]
Solution 1 sounds good 👍

**Comment by AndrewR8** [comment]
I'll open a new one

**Pull request closed without merging**
