### PR TITLE
ADS: Maestro Flow Fix

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL:  https://app.asana.com/0/home/1157893581871899/1203863863772464

### Description
This PR fixes the Maestro flow, so it check the proper text.

### Steps to test this PR
Maestro test

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203863863772464

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2791** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2791" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2791?utm_source=stack-comment).

**Comment by anikiki** [comment]
@malmstein It fails on my local machine (using the latest maestro version - `1.21.3`). Adding a margin at the bottom of the view seems to work. I wonder if this is behaving differently in other environments.

**Comment by cmonfortep** [comment]
I've just triggered the workflow pointing to this branch. You can validate using: https://github.com/duckduckgo/Android/actions/runs/4054134230

**Comment by malmstein** [comment]
Thanks @anikiki !

**Pull request merged**
