### PR TITLE
Add mitigation to feature toggle

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/488551667048375/1202005414608906/f

### Description
This PR adds the AppTP mitigation configuration to feature toggle infra

### Steps to test this PR

_Test feature toggle_
- [x] install internal build
- [x] launch app
- [x] go to settings -> AppTP settings
- [x] scroll down and verify "Bad health mitigation action" is enabled
- [x] enable AppTP
- [x] filter logcat by `AppBadHealthStateHandler`
- [x] go to settings -> AppTP settings -> View Diagnostics Data
- [x] click on BAD HEALTH button
- [x] verify the `Restarting the VPN...` message appears (it can take few seconds to appear)
- [x] click on GOOD HEALTH button
- [x] go to settings -> AppTP settings and disable "Bad health mitigation action" toggle
- [x] go to settings -> AppTP settings -> View Diagnostics Data
- [x] click on BAD HEALTH button
- [x] verify "Feature is disabled, skipping mitigation" message appears in logcat (it can take few seconds)
- [x] Repeat the whole test scenario using `play` build
- [x] verify the outcome is as if "Bad health mitigation action" was enabled

### CODE REVIEW

**Comment by aitorvs** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #1825** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/1825" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Comment by marcosholgado** [comment]
@aitorvs FYI when testing the play flavour I always get `Feature is disabled, skipping mitigation`

**Comment by aitorvs** [comment]
> @aitorvs FYI when testing the play flavour I always get `Feature is disabled, skipping mitigation`. Not sure if the last step is wrong and should say `verify the outcome is as if "Bad health mitigation action" was disabled`. I'm guessing that's the case because all these features afaik should only be enabled in the internal flavour but double checking.

Good catch @marcosholgado. I think I tested internal builds twice rather than testing play 🤦 . Now should be fix. Can you take another look for a second pair of eyes?

**Review by marcosholgado — APPROVED** [review]
LGTM!

**Pull request merged**
