### PR TITLE
adding Polish translation for the app

### PR DESCRIPTION
**Pull request by pwittchen**
In this PR I'm adding Polish translation for the app.
This PR is related to issue #559.

Polish is my mother tongue, so I suppose translation should be correct. :-)

It may require some adjustments in the future depending on the application context. Nevertheless, I tried to take into consideration application context and prepare messages universally for all genders. A few words were hard to translate because I suppose there are no such words in Polish. In that cases, I kept English words, but written in Polish phonetic form, which is common practice for new or unknown words in Polish.

Regards,
Piotr

### CODE REVIEW

**Comment by pwittchen** [comment]
I don't know why CI is failing. From the logs, I see that some kind of emulator or testing device on CI failed to start or execute tests.

**Comment by CDRussell** [comment]
Thanks for providing these suggestions! Before they can be reviewed, you'll need to edit the PR so that it isn't trying to merge into `develop`, but is trying to merge onto `app_translations` instead.

Thanks

**Comment by CDRussell** [comment]
Never mind; I was able to edit the base branch for this PR.

We'll review this soon, thanks!

**Comment by CDRussell** [comment]
@pwittchen did you start from the existing Polish translations we have in place, or start from scratch? 

We need to work from the existing translations to avoid getting into large merge conflicts. Can you confirm if you followed the instructions for contributing translations as outlined here https://github.com/duckduckgo/Android/blob/develop/TRANSLATIONS.md ?

**Comment by pwittchen** [comment]
I started from scratch from develop `branch`. I'll have a look at existing translations and apply them to fix conflicts.

**Comment by CDRussell** [comment]
If you've branched from develop, that will still try to bring in more into the app translations branch.

So really need to start from the app translations branch, and tweak those, so that the resulting PR contains only the changes you've made. If you see other changes in the diff, something is wrong.

**Comment by pwittchen** [comment]
Ok, I checked `feature/app_translations` branch recently (my mistake I didn't do it in the beginning). As far as I see, Polish translations are already there and looks like they're complete, so I suppose my PR is no longer necessary here :).

**Comment by CDRussell** [comment]
Sorry for the confusion! But thank you for taking the time to help.

If there's any problems with the Polish translations in place, please create a PR for it.

I'll close this one for now. Thanks!

**Pull request closed without merging**
