### PR TITLE
Feature/custom url schemes

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/488551667048375/656818431539163
GitHub Issue: https://github.com/duckduckgo/Android/issues/288

Tech Design URL: 
CC: 

**Description**:
Detect custom schemes and determine if an external app can open it or not. If an app is installed which can handle it, we'll prompt the user to ensure they are happy with jumping outside of our app before launching an external app.

**Steps to test this PR**:
1. Search for "uber google play" 
1. Visit the search result for the Google Play Store
1. Click the floating button for "OPEN IN PLAY STORE APP"
1. Test the positive and negative buttons for the dialog which is shown

device-2018-08-07-144630

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by In2deep73** [comment]
Hello @CDRussell ,

I was working on something similar to this for my own personal use.  I hope I am not overstepping my bounds by critiquing this PR, but intent URLs such as:
intent://user?screen_name=DuckDuckGo#Intent;scheme=twitter;S.browser_fallback_url=http%3A%2F%2Ftwitter.com%2FDuckDuckGo;end
specify a fallback URL to navigate to if the app is not installed (the intended action is to navigate to DDG's twitter via the app if installed, else navigate to fallback URL).  Perhaps it would be nice if the fallback URL [val fallbackURL = intent.getStringExtra("browser_fallback_url")] was used when an ActivityNotFoundException is thrown or when the user explicitly chooses to remain in the DDG app.  Other than that, the only other suggestions I could make based on my own experience with this issue is to do something like val package = intent.getPackage() if no app is installed to handle a certain URL and redirect to the market:// URL of said app if intent.getPackage() is not null instead of giving a toast.  Also, maybe a function to determine whether a URL is a 'deep link' to an activity would be nice (deep links to apps use the https or http scheme which make them a bit trickier).  Also, URL's such as the one listed at the bottom of this message redirect to the play store and double load even if the app is installed.  The solution that I've found for this is to pass the entire URL into an intent [and possibly do webView.stopLoading() before launching the intent) and let the OS handle it (this would require a reliable method of determining whether a link is a deep link or if a specialized handler is available).  I hope some of this is helpful to you.  Thank you!

https://reddit.app.link/?campaign=scaled_inference&utm_name=scaled_inference&channel=xpromo&utm_source=xpromo&feature=mweb&utm_medium=mweb&%24og_redirect=https%3A%2F%2Fwww.reddit.com%2F&%24deeplink_path=%2F&%24android_deeplink_path=reddit%2F&mweb_loid=00000000001wfkrzu5&mweb_loid_created=1533163548549&mweb_user_id36=&mweb_user_name=&domain=www.reddit.com&geoip_country=US&user_agent=Mozilla%2F5.0%20(Linux%3B%20Android%209%3B%20Android%20SDK%20built%20for%20x86%20Build%2FPPP4.180612.007)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F67.0.3396.87%20Mobile%20Safari%2F537.36&base_url=%2F&referrer_domain=www.google.com&referrer_url=https%3A%2F%2Fwww.google.com%2F&language=&dnt=false&compact_view=true&adblock=false&session_id=s0EI10481bFKvLfzR7&loid=00000000001wfkrzu5&loid_created=1533163548549&reddaid=4OU25RNO52GONJAB&keyword=control_1&utm_term=control_1&tags=topbutton&utm_content=topbutton

**Comment by brindy** [comment]
@CDRussell 

When the URL is an intent the open in external app functionality leaves the page with the intent URL showing and blank.  I’ve not been able to test this on a device yet, so not sure if it’s because it fails due to the play store not being installed in the emulator, but it also happens when you click cancel. Maybe we can "go back" when these links are clicked?

**Comment by CDRussell** [comment]
@In2deep73 thanks for the detailed suggestions

>I hope I am not overstepping my bounds by critiquing this PR

Not at all! That's why we do these PRs in the open; there's always going to be things we miss. Some of what you said was deliberated omitted as I had limited time to tackle this task; and adding more into its scope would likely have caused the whole task to get delayed. But others you've raised is definitely valid.

>fallback URL to navigate to if the app is not installed

This is definitely something we should add in. I'll get on that.

>if no app is installed to handle a certain URL and redirect to the market:// URL

That might be something to consider for later, but needs a little consideration. Not all of our users get the app from the Play Store, and indeed some definitely don't want to get anything from it.

>maybe a function to determine whether a URL is a 'deep link' to an activity would be nice (deep links to apps use the https or http scheme which make them a bit trickier)

Agreed; I almost considered doing this as part of this task but realised it was extend the scope beyond the time I had available for it. Decided it would be best to come back to this later so it doesn't hold up this custom URL functionality.

>URL's such as the one below [for yelp] result in an **infinite loop** of asking which external app to use

Thanks for flagging this; I'll investigate that.

> I just wanted to try and save some time for you all but at the same time I do not want to disrupt your workflow.

Your efforts are appreciated! Thank you for raising all of the issues you have.

**Comment by CDRussell** [comment]
@brindy 

>When the URL is an intent the open in external app functionality leaves the page with the intent URL showing and blank. I’ve not been able to test this on a device yet, so not sure if it’s because it fails due to the play store not being installed in the emulator, but it also happens when you click cancel. Maybe we can "go back" when these links are clicked?

Indeed, the case is likely because you don't have the Play Store on the emulator (there are emulators you can use which _do_ have the Play Store btw).

As for the cancel case, I did look at stepping the `webView` back but it can get a weird depending on how the custom scheme arrived. Some sites tend to do redirects to different `https` pages before eventually ending on the `intent://` or whatever. I thought it would risk breaking more by trying to be smart around the back navigation.

**Comment by CDRussell** [comment]
>However, this isn't showing the fallback URL for me on an emulator without Play Store installed.

I wouldn't worry about this case; in this situation, Google Play Services is the match but it basically swallows the request to open the Play Store when the Play Store isn't installed. 

>I wonder if we should just show the fallback URL anyway if it's available as well as prompt to launch externally?

My worry here is what happens if the fallback URL, upon loading, also redirects to launch the app or Play Store?

> when I try it with Play Store installed when I hit back from the Play Store I get the prompt again

That's not good. How did you see this? Do you have exact steps to reproduce as I'm not seeing this behaviour?

**Comment by brindy** [comment]
>> when I try it with Play Store installed when I hit back from the Play Store I get the prompt again

> That's not good. How did you see this? Do you have exact steps to reproduce as I'm not seeing this behaviour?

* One Plus One device (Android 5.1.1) (haven't checked it on others)
* Search for "uber play store"
* Open Uber on the Play Store link
* Tap "open in Play Store"
* Play store opens
* Immediately go back
* DDG opens and immediately shows the prompt again

**Comment by CDRussell** [comment]
You got activities being killed off by any chance?

**Comment by brindy** [comment]
> You got activities being killed off by any chance?

Yep! that was it

**Comment by CDRussell** [comment]
Merging this despite there being some rough edges that can be tidied up later.

Rough edges being: 

- we might be able to tidy up the web view when launching external app so it isn't left in a blank-looking state
- links like that reddit one will try and launch two apps; the play store and the reddit app

**Pull request merged**
