### PR TITLE
AppTP dark theme improvements

### PR DESCRIPTION
**Pull request by cmonfortep**
Task/Issue URL: https://app.asana.com/0/488551667048375/1202677003280043/f

### Description
Updates onboarding screen to support dark theme.

### Steps to test this PR

_onboarding dark theme_
- [x] install internal version
- [x] Go to settings
- [x] enabled dark mode, or system default (and use system dark mode)
- [x] go through appTP onboarding
- [x] ensure screens appear in dark mode

### UI changes
| Before  | After |
| ------ | ----- |
image|image

### CODE REVIEW

**Comment by NikolaiLaliLalai48** [comment]
Hello

**Comment by aitorvs** [comment]
@cmonfortep should the AppTP onboarding images have chanced in light mode?

**Comment by cmonfortep** [comment]
> @cmonfortep should the AppTP onboarding images have chanced in light mode?

Only the background. I've posted a before/after comparison in the product review you can check: https://app.asana.com/0/1202705999983703/1202705999983703/1202705999983714

**Comment by aitorvs** [comment]
> > @cmonfortep should the AppTP onboarding images have chanced in light mode?
> 
> Only the background. I've posted a before/after comparison in the product review you can check: https://app.asana.com/0/1202705999983703/1202705999983703/1202705999983714

Left a comment in the product review. Not getting the same I think in light mode

**Comment by cmonfortep** [comment]
Going to update the description so it's more clear @aitorvs

**Comment by cmonfortep** [comment]
@aitorvs I've updated the description, hope now it's more clear.

**Review by aitorvs — APPROVED** [review]
Shows as expected. Good work!

**Pull request merged**
