### PR TITLE
Fix root bookmark import bug

### PR DESCRIPTION
**Pull request by joshliebe**
Task/Issue URL: https://app.asana.com/0/488551667048375/1206477502477978/f

### Description
Fixes an issue where an imported bookmark may sometimes not have a `parentId`

### Steps to test this PR
- [ ] Import the file linked in the task
- [ ] Verify that the bookmarks are imported successfully
- [ ] With sync enabled, verify that the imported bookmarks are synced

### CODE REVIEW

**Comment by joshliebe** [comment]
* `develop`
  * **#4166** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4166?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @joshliebe and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by cmonfortep** [comment]
QQ: sorry if unrelated, but should we include a test case to ensure after import, sync works?

**Comment by joshliebe** [comment]
> QQ: sorry if unrelated, but should we include a test case to ensure after import, sync works?

I've added a test step for sync

**Review by malmstein — APPROVED** [review]
works as expected, thanks @joshliebe!

**Pull request merged**
