### PR TITLE
Test

### PR DESCRIPTION
**Pull request by marcosholgado**
Task/Issue URL: 
Tech Design URL: 
CC: 

**Description**:

**Steps to test this PR**:
1. 
1. 

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by cmonfortep** [comment]
I've just installed this version in my phone, I will be using it and report back any issue.

**Comment by cmonfortep** [comment]
@marcosholgado, I've found an issue (that maybe you are already familiar with) when visiting links that redirect you to the real website. Try any link present in any tweet on your feed, or test it with this one: https://twitter.com/Droidconit/status/1331520566562590722?s=20
- it goes to https://t.co/5VLMAI2xUN?amp=1 
- then https://it.droidcon.com/2020/speakers/
- https://t.co/5VLMAI2xUN?amp=1  has been added to the backstack and pressing back enter in a loop

I think now it's worth trying to explore isredirect/hasgesture and see if we can do something.

**Comment by cmonfortep** [comment]
Changes in navigationStateChange were producing some unexpected behaviors, so I've decided to apply changes in https://github.com/duckduckgo/Android/pull/1020 Please review that PR.

I've also applied the changes in here in case you want to know more.

The problem I was having was that site content was hidden (by spoofing logic) when clicking on any link (inside a website compatible with GPC headers) before previous loading finished.

**Comment by marcosholgado** [comment]
> Changes in navigationStateChange were producing some unexpected behaviors, so I've decided to apply changes in #1020 Please review that PR.
> 
> I've also applied the changes in here in case you want to know more.
> 
> The problem I was having was that site content was hidden (by spoofing logic) when clicking on any link (inside a website compatible with GPC headers) before previous loading finished.

Thanks, I'll close this one then! I also saw some weird behaviour with this branch where the progress bar didn't seem to work in some specific cases.

**Pull request closed without merging**
