### PR TITLE
FFS: Fix old bookmarks migration

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/0/1204733967627383/f

### Description
Fixes old migration issue, see task for more info

### Steps to test this PR
Tests pass

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3704** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3704" target="_blank">Graphite</a> 
    * **PR #3705** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3705" target="_blank">Graphite</a> 
      * **PR #3721** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3721" target="_blank">Graphite</a>  👈
      * **PR #3707** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3707" target="_blank">Graphite</a> 
        * **PR #3710** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3710" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3721?utm_source=stack-comment).

**Comment by cmonfortep** [comment]
@malmstein can you add test cases to the description? Thanks!

Conflicts: You will have conflicts because FFS migration will only happen to internal users.

**Comment by malmstein** [comment]
@cmonfortep there are test cases added to the migration tests. What do you not find clear?

**Review by malmstein — COMMENTED** [review]
@cmonfortep this is ready for review. Conflicts have been resolved.

**Review by cmonfortep — COMMENTED** [review]
Left just one comment to optimise the logic.

Tested and works fine, except for one scenario.

Steps:
- Using 5.150.0: Add twitter and verge as favorites, cnn.com as favorite and bookmark, nba as bookmark.
- Update to 5.177.1: Twitter and Verge are in favorites_root, cnn.com in favorites_root and bookmarks_root, nba in bookmarks_root

Wanted to test the migration in the case of a user that has "fixed" something:
- visited verge.com
- it's displayed as favorite, not as bookmark (expected as it has only a relations with favorites_root)
- add it as bookmark -> This has created a new entity and relation with bookmark_root (My expectation was to create only the relation, but we can't fix that here)

- update to this branch: Migration worked well. But in the case of verge.com, we now have 2 verge.com in bookmarks_root (the one created in the previous step, the one we have just migrated)

Proposal:
Inside `migrateFavorites` we already have some logic to detect a bookmark with the same url, can we do something similar here? Like detecting if there's already a bookmarks with same title and url, and just dedup?

For internals with sync enabled, anything we change in this migration is just creating a new relation, which doesn't change the timestamp of any folder entity. That means that it will not sync, something to consider?

**Comment by malmstein** [comment]
Replaced witgh https://github.com/duckduckgo/Android/pull/3846

**Pull request closed without merging**
