### PR TITLE
fix #236

### LINKED ISSUE #236: Last favourite not displaying when recent lists is empty
This first screenshot shows my recent and favourites:
screenshot_20160515-173152

However, when I remove all my recent searches, the last favourite is not displayed either:
screenshot_20160515-173207
Thanks in advance.

### PR DESCRIPTION
**Pull request by fgei**

### CODE REVIEW

**Comment by nilnilnil** [comment]
How long would it take to add tests for this?

**Comment by fgei** [comment]
I'm not sure since I don't have much experience with android testing
definitely some time since we should set up the project for unit testing.
if you want I can start looking into it

**Comment by nilnilnil** [comment]
@sreilly @fgei what are you experiences with Android test coverage? For the main search engine code, it was kind of annoying to setup, but had paid dividends. I am trying to do the math for mobile now.

**Comment by sreilly** [comment]
Hi @nilnilnil neither Francesco nor I have much experience with testing Android apps but we're happy to implement an automated system. In the last year or so a bunch of libraries have come out that should make testing views and app states easier.  Maybe we should start by implementing a couple of basic tests and see how it works out? // @fgei

**Pull request merged**
