### PR TITLE
Add support for email protection logout

### PR DESCRIPTION
**Pull request by alistairjcbrown**
Task/Issue URL: https://app.asana.com/0/0/1202050175851750/f

### Description

Updates Android browser to support log out from the Email Protection web app. Supports post message back to the Email Protection web app whenever log out occurs.

### Steps to test this PR

- [x] Run `git submodule update submodules/autofill`
- [x] Run `git submodule`
- [ ] Commit should be `a4bff09eb0f3b14005c3960c590ec4efb9c5a23c`

_Sign Out propagates correctly_
- [x] Install the app from this branch.
- [x] Go to `duckduckgo.com/email` and sign in.
- [x] Create two new tabs using different sites (i.e. SERP, cnn) and stay in one of them.
- [x] Go to Settings -> Email Protection
- [x] Click on `Remove from Device`
- [x] Go back to the browser and then to the tab with `duckduckgo.com/email`
- [x] Site should automatically sign you out.

_Sign Out from dashboard_
- [x] Go to `duckduckgo.com/email` and sign in.
- [x] Go to Settings -> Email Protection
- [x] You should be logged in
- [x] Go back to the browser and to the tab with `duckduckgo.com/email`
- [x] Click in Sign Out
- [x] You should be signed out from the site
- [x] Go to Settings -> Email Protection
- [x] You should be sign out

_Sign Out from settings_
- [x] Go to Settings -> Email Protection
- [x] Click on `I already have a Duck address` and sign in using that screen. Do not open the link from the emai but copy&paste the passphrase instead.
- [x] Click in Sign Out
- [x] You should be signed out from the site

### CODE REVIEW

**Comment by marcosholgado** [comment]
Thanks @alistairjcbrown, leave this to me :)

**Comment by alistairjcbrown** [comment]
Thanks @marcosholgado 😅 -- I'll assign the task over to you! 👍

**Comment by alistairjcbrown** [comment]
@marcosholgado Updated autofill to use the latest release 👍

**Comment by marcosholgado** [comment]
> The autofill submodule seems to have been updated...I guess we should revert that change before merging?
> 
> Approving anyway as works as expected and code looks good

The submodule update is expected :) Thanks!

**Pull request merged**
