### PR TITLE
Update to AGP 7

### PR DESCRIPTION
**Pull request by joshliebe**
Task/Issue URL: https://app.asana.com/0/414730916066338/1200759779300446/f

### Description
This PR updates the Android Gradle Plugin to ~7.1.3~ 7.0.4 (latest supported by IntelliJ IDEA).

### Steps to test this PR
1. All unit tests should pass.
2. Run through the app and check that there isn't any unexpected behavior.

**Smoke test**:
- Onboarding CTAs
- Add bookmarks and favorites
- Disable/enable privacy protection
- Share feedback
- Fireproof a site and clear all data
- Opening multiple tabs (and closing tabs + undo)
- Enable App Tracking Protection

### CODE REVIEW

**Comment by CDRussell** [comment]
@joshliebe have you got this working in `IntelliJ IDEA`? When I try to build the project, I see the same error message that's been there a while, indicating the IDE doesn't support AGP 7 yet.

>This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.

I see this on both the latest stable and latest preview versions of IDEA. I've tried to find some definitive statement on what should be supported where, but I'm struggling to be honest; it's unclear what the current status is.

My intuition is that it should work by now, and maybe I have a local environment issue preventing it, so would appreciate hearing from you if it works on your side. If it is a general problem, we'll need to delay merging this PR since it will be a blocker for people using IDEA.

**Comment by CDRussell** [comment]
cc @aitorvs as a fellow IDEA user; does this branch build for you in the IDE?

**Comment by CDRussell** [comment]
Further update, after some digging it looks like AGP 7.0.x is supported, but not 7.1.x as we have in this PR. I'll test some more, and push a commit to use the latest 7.0.x version if that works

**Comment by aitorvs** [comment]
Yup, only 7.0.x is supported now for IntelliJ IDE

**Review by CDRussell — APPROVED** [review]
Working fine with AGP 7.0.4, against 2022.1.1 IntelliJ IDEA preview

**Comment by joshliebe** [comment]
@CDRussell Thanks for testing this on IntelliJ, I only tried AS. Happy we could get it to 7 though 🎉🙌

**Comment by CDRussell** [comment]
> @CDRussell Thanks for testing this on IntelliJ, I only tried AS. Happy we could get it to 7 though 🎉🙌

Looking back at all the subtasks needed, it was a surprisingly long journey. Thank you for getting it across the line 🏁

**Pull request merged**
