### PR TITLE
Translations for settings screen changes

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/488551667048375/1202807460291285/f 

### Description
Translations for the settings screen

### Steps to test this PR
n/a

### CODE REVIEW

**Comment by CDRussell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2179** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2179" target="_blank">Graphite</a> 
    * **PR #2187** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2187" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2187?utm_source=stack-comment).

**Comment by Sheraldo99** [comment]
So many things

**Comment by Sheraldo99** [comment]
Cosby

**Comment by Sheraldo99** [comment]
I le iti

**Comment by Sheraldo99** [comment]
I don't think it was a good idea

**Review by karlenDimla — APPROVED** [review]

**Pull request merged**
