### PR TITLE
Improve filename guesses when MIME type provided or dots are in the path

### PR DESCRIPTION
**Pull request by asilvr**
## Description

This PR addresses a few issues related to the filename guessing method used in the Download Manager. To guess the filename, this PR improves usage of the MIME type when a URL path segment matches the MIME type, is ambiguous, or contain dots.

This PR also adds test coverage for when MIME types are provided -- most of the existing logic was written assuming no MIME types, which left a gap in proper filename guesses. Saving the file with a guessed name that is closer to what the user expects is a user experience improvement, and also avoids replacing files with the same name unintentionally.

Below are a few issues and their expected and actual behavior.

### Issue: Not utilizing MIME types appropriately

For a URL such as `https://example.com/files/realFilename.pdf` and a valid MIME type (e.g. `application/pdf`):

- Expected filename: `realFilename.pdf`
- Actual filename: `files.pdf`

### Issue: Not appropriately handling dots in the URL path:

For a URL such as `https://example.com/files.folder/realFilename.pdf` and a valid MIME type (e.g. `aplication/pdf`):

- Expected filename: `realFilename.pdf`
- Actual filename: `files.folder`

For a URL such as `https://example.com/files.folder/realFilename.pdf` and no valid MIME type provided:

- Expected filename: `realFilename.pdf`
- Actual filename: `files.folder`

### Issue: Not appropriately handling ambiguous filenames:

For a URL such as `https://example.com/files/realFilename` and a valid MIME type (e.g. `application/pdf`):

- Expected filename: `realFilename.pdf`
- Actual filename: `files.pdf`

### Steps to test this PR

1. Navigate to a URL which contains a `.` in the path of an attachment

I've created these for testing, which I'll remove if/when this PR is merged:

 - https://d1x9zcshh2aa46.cloudfront.net/abc.def/example.pdf (saves as `abc.def`)
 - https://d1x9zcshh2aa46.cloudfront.net/abc.123/example.pdf (saves as `abc.123`)
 - https://d1x9zcshh2aa46.cloudfront.net/123.abc/example.pdf (saves as `123.abc`)
 - https://d1x9zcshh2aa46.cloudfront.net/123.456/example.pdf (saves as `123.456`)
 - https://d1x9zcshh2aa46.cloudfront.net/abc.pdf/example.pdf (saves as `abc.pdf`)

2. Prior to this PR, none of these files will save as `example.pdf`. With this PR, they'll all save as `example.pdf`. Note that none of these have a `Content-Disposition`, implying they're `inline` and don't have a filename specified.

### CODE REVIEW

**Comment by cmonfortep** [comment]
@asilvr thanks for the contribution. 

Could you align with develop? There's a check failing in one of our github actions, but it should already fixed in develop. Thanks!

**Review by cmonfortep — APPROVED** [review]
👍  all good. Thanks!

**Comment by asilvr** [comment]
I'm working on hardening this a little bit, as the current implementation is a little too naive and has some gaps. I'll let you know when I think it's good for a re-review+merge.

**Comment by cmonfortep** [comment]
Thanks for the heads-up. We are currently on a special code freeze, and we will not merge any PR for the next 2 weeks. That's why this one is in standby.

If you want to improve it, feel free to do so. I'm ok if you want to open a second PR for that, or just push changes into this one.

Another comment from my side. We are having internal conversations to move away from Download Manager (which is the main reason why we need to guess the file name before we start the download). It's not going to happen in the short-term...but I'm convinced that project will happen sooner than later. This is just for you in case you want to timebox your improvements, we know it will be deprecated in the future.

**Comment by asilvr** [comment]
Thanks @cmonfortep!

Also, appreciate the context on moving away from Download Manager to help timebox. I’ll probably spend no more than a day or so further on this.

**Comment by cmonfortep** [comment]
@asilvr I see CI is failing when running unit tests. is it failing for you in local?

**Comment by cmonfortep** [comment]
Just in case it helps...This is the report from commit 8fd98f2cc14bf1e6322a640879543a39bb4248d6

image

**Comment by asilvr** [comment]
Thanks @cmonfortep! For some reason, I can't find those granular, per-test failures. Is that expected for non-maintainers?

I'm not seeing these failures locally, but my hunch is that it has to do with the API version in the test target. I'm looking a little closer at it. If I can't get any further, I'll revert to the approach from the beginning of the PR, and work on the extra logic in a separate one.

**Comment by cmonfortep** [comment]
More than expected, just a constraint of using bitrise I think. I will check if there's any way to make those reports available to external contributors.

Going to check out your branch and see if I have the same issues.

**Comment by cmonfortep** [comment]
@asilvr it's failing for me in local as well, so I don't know what can be the issue on your side. I've executed the tests on an emulator (Pixel_5_API_28(AVD) - 9).

**Comment by asilvr** [comment]
@cmonfortep I inadvertently deleted this remote branch (then restored it), which I guess is sort of a signal to me to call time on the timebox 😄 

I've pushed up #1547 which is the minimal change set to get this moving forward without any further guessing improvements that I was trying to add in this PR. I'll monitor that PR, and I suspect that most of my CI issues were related to my additional logic.

**Comment by cmonfortep** [comment]
Awesome @asilvr, good call on this.

**Comment by asilvr** [comment]
Going to close this PR. I believe #1547 gives the most short term value-add, and stays relatively maintainable until new download management is added to this project.

**Pull request closed without merging**
