### PR TITLE
Migrate PrivacyDashboardHybridActivity to nav library

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/0/1204415151858378/f

### Description
Ditto

### Steps to test this PR
Smoke tests for privacy dashboard screen

### CODE REVIEW

**Comment by aitorvs** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3072** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3072" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3072?utm_source=stack-comment).

**Review by cmonfortep — COMMENTED** [review]
FYI: it crashes when trying to open the privacy dashboard
`   Caused by: java.lang.NullPointerException
        at com.duckduckgo.privacy.dashboard.impl.ui.PrivacyDashboardHybridActivity.configureObservers(PrivacyDashboardHybridActivity.kt:115)
        at com.duckduckgo.privacy.dashboard.impl.ui.PrivacyDashboardHybridActivity.onCreate(PrivacyDashboardHybridActivity.kt:111)`

**Comment by aitorvs** [comment]
> FYI: it crashes when trying to open the privacy dashboard ` Caused by: java.lang.NullPointerException at com.duckduckgo.privacy.dashboard.impl.ui.PrivacyDashboardHybridActivity.configureObservers(PrivacyDashboardHybridActivity.kt:115) at com.duckduckgo.privacy.dashboard.impl.ui.PrivacyDashboardHybridActivity.onCreate(PrivacyDashboardHybridActivity.kt:111)`

I think they're fixed now

**Review by cmonfortep — APPROVED** [review]
LGTM, smoke tested and it works 👍

**Pull request merged**
