### PR TITLE
Add Scorecard

### PR DESCRIPTION
**Pull request by subsymbolic**
Asana Issue URL: https://app.asana.com/0/488551667048375/495411750237128

## Description
• Adds a scorecard to the app
• Pull out ui components from DashboardViewModel and moves them into stand alone renderers

## Steps to Test this PR:
TEST ONE:
1. Visit duckduckgo.com
1. Tap on the privacy grade
1. See that the scorecard is all good

TEST TWO:
1. Visit cnn.com
1. Tap on the privacy grade
1. See that the scorecard is all bad but DOES NOT display "Site is a major tracker network" displayed

TEST THREE:
1. Visit facebook.com
1. Tap on the privacy grade
1. See that the scorecard displays "Site is a major tracker network" displayed

### CODE REVIEW

**Comment by brindy** [comment]
Zeplin shows detail arrow and back arrow which appear to be missing.  I'm not sure an arrow is even appropriate given the transitions so maybe worth discussing later before we merge.

**Comment by brindy** [comment]
screenshot_1515598236

Isn't showing "site is major tracker network" for Facebook - could be because it was redirected to the mobile site?

**Comment by subsymbolic** [comment]
Good point! The arrows are part of the navigation that we had questions around and decided to go with the most "basic android defaults" for now. Let's ask Mike to come to standup today and see if he feels it's ok.

**Comment by subsymbolic** [comment]
Oh thanks for following that up. I couldn't reproduce the facebook issue either - I tried a few times and I saw it listed as major tracker network each time.

There's an inprogress task that will stop us from seeing the dashboard until we have all the data sources, so any confusion caused by incomplete data will hopefully be avoided in the future.

**Comment by subsymbolic** [comment]
@brindy I've captured the nav question for Mike in https://app.asana.com/0/414730916066338/519895400114335. Let me know if there's anything else you need for this PR.

**Pull request merged**
