### PR TITLE
UI for the showing/hiding/dismissing/accessing the survey

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/0/1207179707350729/f 

### Description
Adds an autofill survey to the autofill management screen. The survey will be available for a few app versions and removed after a few weeks. 

- We decided to hardcode it for the first one on the assumption we wouldn't use this much again. 
- If it seems like something we'd do more often then will tie it into remote config

#### Check the survey prompt shows up
- [ ] Visit autofill management screen (`Settings` -> `Passwords`)
- [ ] Verify you see the survey prompt
- [ ] Verify `m_autofill_management_screen_visit_survey_available` pixel fires

#### Check that it keeps showing up
- [ ] Leave the screen and return; verify prompt is still there

#### Check dismiss behaviour 
- [ ] Tap the ❌ on the survey; verify it disappears
- [ ] Leave the screen and return; verify it does not come back

#### Check you can take the survey
- [ ] Reset app data, and return to autofill management screen
- [ ] This time, choose to take the survey; verify the survey loads in a tab and you can complete it
- [ ] Return to autofill management screen; verify the survey prompt is gone

### CODE REVIEW

**Comment by CDRussell** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4475?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4476** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4475** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4475?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4474** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4474?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CDRussell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cmonfortep — APPROVED** [review]
LGTM 

Few comments when testing:

when accessing passwords without local auth, I don't see the survey (expected) but pixel is fired.
image

Another thing is that conflicts with the onboarding (I guess both new and old). Surveys usually appear after onboarding. Can we include that check? In the screenshot is asking you to fire button in the middle of the survey.
image

While taking the survey got this:
image

**Comment by CDRussell** [comment]
re onboarding prompts, will discuss in [Do we need to wait until user has finished onboarding prompts?](https://app.asana.com/0/1207220144106432/1207220144106432/f)

**Comment by CDRussell** [comment]
### Merge activity

* **May 9, 5:30 PM EDT**: @CDRussell started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/4475).

**Pull request merged**
