### PR TITLE
Show "... type URL"

### PR DESCRIPTION
**Pull request by Knhash**
Change the ActionBar hint from "Search DuckDuckGo" to "Search DDG or type URL"

- Because direct typing of URL works, as in a browser; lets the user know

### CODE REVIEW

**Comment by sreilly** [comment]
assigned @thm to review as that text is mostly a style decision, and he's extra stylish :)

**Comment by tagawa** [comment]
Would this text be better as "Search DDG or type URL", if it's not too long?

**Comment by edgesince84** [comment]
hey @Knhash, I wanted to see if you still planned on finishing this up - we really appreciate your contribution and want to see this go live. We're closing up old PRs in the next week, so let me know if I should leave this open for you!

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by Knhash** [comment]
Hi @edgesince84, I'm not sure what you mean by finishing it up. Isn't this just a merge away from deployment ?

**Comment by tagawa** [comment]
Hi @Knhash. I think there's been a bit of confusion, and sorry for the delay so far.

If @thm is happy with the new string ("Search DDG or type URL") then we can merge. @thm - what do you think?

**Comment by thm** [comment]
@Knhash @tagawa Excuse the late reply, completely missed this one. I'm not a big fan of shortening "DuckDuckGo" to "DDG" as shortening it takes away recognizability. I do agree that it's nice to remind people that you can type in a URL as well. Is there any way we can show "DuckDuckGo" in full when we have the space available and shorten it to "DDG" on smaller screens (eg. iPhone 5<)? cc @sreilly

**Comment by Knhash** [comment]
Hey @thm
I have changed the implementation to suggest the full hint ("Search DuckDuckGo or type URL") when possible.

**Comment by Knhash** [comment]
Hi  @thm 
I also un-commented the intent filter for handling external URLs. I didn't find any immediate bugs and was wondering why it was removed in the first place (the code to handle the intent was already present)

**Comment by thm** [comment]
Thanks @Knhash! @sreilly can you test/merge this and include it with the next Testflight?

**Comment by sreilly** [comment]
@thm sure!  I've assigned to @fgei who's more qualified than me to check it.

**Comment by thm** [comment]
@sreilly sorry, I was mixing up the platforms! :)

**Comment by fgei** [comment]
thanks @Knhash!
can you change the onion kit commit to the previous one, now it seems to point to a non existing commit!

**Comment by Knhash** [comment]
Hey @fgei
I haven't made any commits related to onion kit, but it's probably because
I downloaded the sub module before committing. Shall I just clean the
project and upload again?

**Comment by fgei** [comment]
yep @Knhash, that would be perfect, thanks!

**Comment by Knhash** [comment]
@fgei, I checked out master in Android Studio and committed the changes. Turns out I was on some Onion kit branch. Sorry about that.

**Comment by Knhash** [comment]
@thm @fgei Updates on the merge?

**Comment by fgei** [comment]
sorry @Knhash I forgot bout this PR!
the onionkit is still pointing on the wrong commit, if you can revert that and all the gradle changes it would be nice so I can merge it, we should handle that in a different PR thanks

**Comment by Knhash** [comment]
Alright. I'll close this PR and open a new one with the changes.

**Pull request closed without merging**
