### PR TITLE
Site Permissions: Code Clean up

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/72649045549333/1208702063802241/f

### Description
This PR finishes cleaning up the code from Site Permissions.
- Moves strings to site permissions module
- Moves Activities to site permissions module
- Removes old LocationPermissions

### Steps to test this PR
Navigate to Site Permissions screen and smoke test it

### CODE REVIEW

**Comment by malmstein** [comment]
* **#5363** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5363?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5363?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `develop`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by nalcalag — COMMENTED** [review]
Clean up looks good to me and works as expected! However, it seems the strings files got messed up, with some English words showing in all languages. 
I’d recommend removing all the string changes, merge this PR and maybe opening a new one with the original strings changes from this branch?

**Review by nalcalag — APPROVED** [review]
Synced with @malmstein and most of strings changes come from an external change not related to this PR.
Tested _Site Permissions_ in another language and works as expected

**Comment by malmstein** [comment]
Thanks @nalcalag !

**Pull request merged**
