### PR TITLE
GHA: Use new public action

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/1157893581871903/1205649493845651

### Description
Replace the custom GHA we were using from the public malmstein repo to the duckduckgo one

### Steps to test this PR
Smoke tests workflows

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3639** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3639" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3639?utm_source=stack-comment).

**Review by marcosholgado — APPROVED** [review]
LGTM

**Review by marcosholgado — CHANGES_REQUESTED** [review]
Not working :)

Unable to resolve action `duckduckgo/native-github-asana-sync@v1.0`, unable to find version `v1.0`

**Comment by malmstein** [comment]
Thanks @marcosholgado , it’s working now… seemed to be an issue with the tag itself.

**Review by marcosholgado — APPROVED** [review]
LGTM

**Pull request merged**
