### PR TITLE
Added new queryIntentServices() method for API >= 33

### PR DESCRIPTION
**Pull request by nalcalag**
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204307243474497/f

### Description
Adopt the new [queryIntentServices()](https://developer.android.com/reference/android/content/pm/PackageManager#queryIntentServices(android.content.Intent,%20android.content.pm.PackageManager.ResolveInfoFlags)) on >= API 33

### Steps to test this PR

On >= Android 13 / Tiramisu

** On a device with Play Services**
- [x] Execute `packageManager.queryIntentServices(serviceIntent, PackageManager.ResolveInfoFlags.of(0))`
- [x] Verify it returns at least one result

** On an emulator without Play Services**
- [x] Execute `packageManager.queryIntentServices(serviceIntent, PackageManager.ResolveInfoFlags.of(0))`
- [x] Verify it returns zero results

### CODE REVIEW

**Comment by nalcalag** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3042** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3042" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3042?utm_source=stack-comment).

**Comment by CDRussell** [comment]
@nalcalag, this is assigned to me but still in draft. ready to review?

**Comment by nalcalag** [comment]
> @nalcalag, this is assigned to me but still in draft. ready to review?

I left it as a draft because I didn't include any steps to test it, as I am unsure of the best way to proceed. However, I believe you might know how to test it, so I will change it to "Ready for Review" 👍

**Review by CDRussell — APPROVED** [review]
Tested against newer APIs on a device (with Play Services) and an emulator without; all working as expected

**Comment by CDRussell** [comment]
For posterity, I added testing steps to the PR description.

**Pull request merged**
