### PR TITLE
Migrate device-auth modules to live inside autofill-impl

### PR DESCRIPTION
**Pull request by CDRussell**
Task/Issue URL: https://app.asana.com/0/488551667048375/1205211960929383/f 

### Description
Originally, `device-auth` modules were created separately from `autofill`. The thinking was that the separation was good and perhaps `device-auth` might be used elsewhere, but to date it's just `autofill` that uses it. 

This PR moves `device-auth-api` and `device-auth-impl` inside of `autofill-impl`, treating device auth as an implementation  detail of autofill.

### Steps to test this PR

- [x] Smoke test autofill, ensuring the device auth still functions as normal
- [ ] Enter the _auth grace period_ is still invalidated when leaving the app: 
    - [x] visit logins when you have some saved, and verify you are prompted to auth against device auth
    - [x] quickly leave logins and return; verify you are **not** prompted to device auth
    - [x] quickly tap the home button and return to logins; verify you **are** now prompted

### CODE REVIEW

**Comment by CDRussell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3687** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3687" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3687?utm_source=stack-comment).

**Review by karlenDimla — COMMENTED** [review]
Just a small question: Will moving around translated files not cause any issues with smartling?

**Review by karlenDimla — APPROVED** [review]
Just one small question. Everything else looks good and worked as expected.

**Comment by CDRussell** [comment]
> Just a small question: Will moving around translated files not cause any issues with smartling?

I _think_ it will be fine, but good question. will double check if anyone else knows before merging.

**Pull request merged**
