### PR TITLE
Automatically codegen Android-types Dagger Components

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/414730916066338/1202096781734430/f

### Description
Use anvil-compiler to generate the dagger subcomponents.

USage:

```kotlin
@ContributesDdgSubcomponent(ActivityScope::class)
class MyActivity : DuckDuckGoActivity() {...}
```

### Steps to test this PR

_Smoke tests_
- [x] Install from this branch and smoke test the browser and AppTP screens

### CODE REVIEW

**Comment by aitorvs** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #1852** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/1852" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/1852?utm_source=stack-comment).

**Review by karlenDimla — COMMENTED** [review]
There's a few remaining components that hasn't been migrated:
- AuditSettingsActivityComponent
- DevSettingsActivityComponent
- ExceptionRulesDebugActivityComponent
- VpnInternalSettingsActivityComponent

Otherwise, app behaves as usual and code looks good.

**Comment by aitorvs** [comment]
> * VpnInternalSettingsActivityComponent

Remove all except `VpnInternalSettingsActivityComponent` because we can't. I realised that, even though the `VpnInternalSettingsActivity` is in the `:vpn-internal` module, the `VpnInternalSettingsActivityComponent` is in the `:app` module. The reason for that is that there's a visibility problem at build time and Dagger does not see one of the generated bindings, in particular the `VpnStateCollector`. 
That's why we put that component in the `:app` module, so that dagger tries to do the binding at the very last moment.

The automatic codegen of that component will generate it in the `:vpn-internal` module, and then dagger won't be able to bind the dependency.

To verify that this is not a problem of the codegen you can do the following, in `develop`, move the `VpnInternalSettingsActivityComponent` anywhere in the `vpn-internal` module and execute:

```bash
> ./gradlew clean;rm -rf build-cache/
> ./gradlew clean assembleID
```

Build should fail (same failure if you try to automatically codegen this component in this branch)

I would propose to merge this PR because it still adds value, and tackle that component separately in a different task.

What do you think?

**Review by karlenDimla — APPROVED** [review]
Looks good to me!

**Pull request merged**
