### PR TITLE
Update copy and request translations

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/1204920898013511/1208577246155728/f

https://dashboard.smartling.com/app/projects/b01b53ede/account-jobs/b01b53ede:hlnez7ekeaqw?filter=ALL&projectIds[]=b01b53ede

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5260?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5260** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5260?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#5237** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5237?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5171** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5171?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 4 other dependent PRs ([#5172](https://github.com/duckduckgo/Android/pull/5172) <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5172?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#5187](https://github.com/duckduckgo/Android/pull/5187) <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5187?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#5213](https://github.com/duckduckgo/Android/pull/5213) <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5213?utm_source=stack-comment-icon" target="_blank">Graphite</a> and 1 other)
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CrisBarreiro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by marcosholgado — CHANGES_REQUESTED** [review]
@CrisBarreiro this file is wrong.

It's missing the smartling instructions at the top:

```
<!-- smartling.entity_escaping = false -->
<!-- smartling.instruction_attributes = instruction -->
```

And the file name is the other way around, should be `strings-broken-site.xml`, this is why the automation is not picking it up. Note when you change the file name, it will run through the automation.

**Comment by CrisBarreiro** [comment]
Done!

**Comment by CrisBarreiro** [comment]
> @CrisBarreiro this file is wrong.
> 
> It's missing the smartling instructions at the top:
> 
> ```
> 
> 
> ```
> 
> And the file name is the other way around, should be `strings-broken-site.xml`, this is why the automation is not picking it up. Note when you change the file name, it will run through the automation.

@marcosholgado that's fixed now and the automation is working properly. Could you please review?

**Pull request closed without merging**
