### PR TITLE
Omnibar Refactor: Extract LegacyOmnibar

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/1174433894299346/1208315670817078/f

### Description
Step 1 to refactor omnibar. See https://app.asana.com/0/1174433894299346/1208305414363523

### Steps to test this PR
Use the app as you’d normally do.
Smoke tests, etc

### CODE REVIEW

**Comment by malmstein** [comment]
* **#5011** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5011?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @malmstein and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by anikiki — APPROVED** [review]
LGTM :+1: Smoke tested, all good :tada:

**Comment by malmstein** [comment]
Waiting for https://github.com/duckduckgo/Android/pull/4978 to be merged

**Comment by malmstein** [comment]
https://github.com/duckduckgo/Android/pull/4978 is now merged so I’ll merge this one and start the ball rolling

**Pull request merged**
