### PR TITLE
Bump room version to fix build in M1 builds

### PR DESCRIPTION
**Pull request by aitorvs**
Task/Issue URL: https://app.asana.com/0/414730916066338/1201403896220544/f

### Description
Room has a [bug](https://issuetracker.google.com/issues/174695268?pli=1) prior to 2.4.0-alpha03, in the native SQL library, that makes it not compile in M1 chips.

This PR just bumps room to unblock M1 developers

### Steps to test this PR
If you're amongst the lucky to have an M1, just build and enjoy :rocket:

### CODE REVIEW

**Comment by aitorvs** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #1560** 
    * **PR #1561**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

**Comment by CDRussell** [comment]
I'm a little confused why this is related to #1560, is it supposed to be merging into the `install_tools` branch?

**Comment by CDRussell** [comment]
I'm a little confused why this is related to #1560, is it supposed to be merging into the `install_tools` branch?

**Review by CDRussell — APPROVED** [review]
Tested the new Room version and it looks good.

**Comment by aitorvs** [comment]
> I'm a little confused why this is related to #1560, is it supposed to be merging into the `install_tools` branch?

oh no, sorry about the confusion, we can merged both independently. 
That message appeared automatically just because I (mistakenly) stacked those PRs together

**Pull request merged**
