### PR TITLE
issue #914  bottom-anchored content and  canvas drawing fixed

### PR DESCRIPTION
**Pull request by AndroidPoet**
Task/Issue URL: https://github.com/duckduckgo/Android/issues/914

### Description
There were two issues:
(1.)When we visit Reddit or Twitter they show bottom-anchored content which got partially hidden.
(2.)Website like  https://sketch.io/sketchpad/ contains canvas was not working properly, because someone added the AppBar hide functionality to fix the above issue, which was not the correct approach.

### Steps to test this PR
(1) .First issue fix can be tested by visiting Twitter and Reddit without login.
(2.) We can test the second issue fix by visiting  https://sketch.io/sketchpad/  and drawing something on canvas.

_Feature 1_
- [ ]
- [ ]

### CODE REVIEW

**Comment by cmonfortep** [comment]
I will take a look (right now I'm afk). 

Just to set expectations:
- when the fire button is highlighted, the url bar should be pinned (doesn't hide on scroll)
- on any other scenario, the url bar should react when the user scrolls (hide/show, but not pinned to the top)

**Comment by AndroidPoet** [comment]
> I will take a look (right now I'm afk).
> 
> Just to set expectations:
> 
> * when the fire button is highlighted, the url bar should be pinned (doesn't hide on scroll)
> * on any other scenario, the url bar should react when the user scrolls (hide/show, but not pinned to the top)

I have checked all the browser they use pinned URL bar. if you want to scroll the URL bar it will always cause issues with the canvas content.

**Comment by AndroidPoet** [comment]
if I am not wrong before someone added this scrolling url bar, to fix that  bottom-anchored content , even duckduckgo also used pinned URL bar

**Comment by cmonfortep** [comment]
> > I will take a look (right now I'm afk).
> > 
> > Just to set expectations:
> > 
> > * when the fire button is highlighted, the url bar should be pinned (doesn't hide on scroll)
> > * on any other scenario, the url bar should react when the user scrolls (hide/show, but not pinned to the top)
> 
> I have checked all the browser they use pinned URL bar. if you want to scroll the URL bar it will always cause issues with the canvas content.
> 

Ideal scenario will be to do the same as in Chrome. They also hide/show the url bar when user scrolls

**Comment by AndroidPoet** [comment]
If you can test once I don't think they ever hide that. I have built a browser from scratch, I don't think hiding the URL bar is a very good security practice anyone can use a phishing attack to show a fake web page with different URL,if the URL bar is there I can constantly check the URL I am at.App i have built with encrypted content :https://play.google.com/store/apps/details?id=com.artis.browser

**Comment by cmonfortep** [comment]
@AndroidPoet will take a look thanks. Just to set expectations, I'm planning to review it beginning next week.

**Comment by cmonfortep** [comment]
@AndroidPoet I see we still have the toolbar pinned to the top. As I commented, expected behavior is to mimic what chrome or similar browser do. 

Here's a gif of the behavior on Chrome as an example:
chrome-urlbar

**Comment by AndroidPoet** [comment]
> @AndroidPoet I see we still have the toolbar pinned to the top. As I commented, expected behavior is to mimic what chrome or similar browser do.
> 
> Here's a gif of the behavior on Chrome as an example: chrome-urlbar [ ](https://user-images.githubusercontent.com/4747865/173052994-eec3ea1f-1fc7-4203-ab4b-b0d732f8be0c.gif) chrome-urlbar [ ](https://user-images.githubusercontent.com/4747865/173052994-eec3ea1f-1fc7-4203-ab4b-b0d732f8be0c.gif)

I see they have this Scrolling Behavior for Appbar i guess i can fix this i got the idea.

**Comment by AndroidPoet** [comment]
I have explored this and found a solution now the task is how to migrate those changes without touching the main files. I am trying to implemented that.

**Comment by AndroidPoet** [comment]
Update: Hi! @cmonfortep I spent last week on this issue only, I have almost achieved the solution.
I need to add a few more checks for the desired result+perfromance. 

https://user-images.githubusercontent.com/13647384/174241476-fd6907a7-99f3-48e5-ae85-ed8763c27520.mp4

**Comment by cmonfortep** [comment]
Looks promising! Looking forward to seeing the final version.

I can see some blank space when scrolling, is that the optimization/performance you are talking about?

**Comment by AndroidPoet** [comment]
Yes,that blank space is the problem I am trying to fix and improve performance

**Comment by AndroidPoet** [comment]
Hi! @cmonfortep! this is the best solution, there is still a minor glitch that can be fixable in the future,If this is acceptable, I would love to implement it.

https://user-images.githubusercontent.com/13647384/174943705-883c6318-4377-48bb-9cec-0a81cbccbc25.mp4

**Comment by AndroidPoet** [comment]
> Thanks @AndroidPoet, I will take a look this week.

I have not implemented it yet. Let me know your views on above video.

**Comment by cmonfortep** [comment]
If you can push the code I can test it and give some feedback. Yeah, on the video I can see it's not perfect but maybe good enough to fix the issue.

**Comment by cmonfortep** [comment]
@AndroidPoet pinging here in case you missed my last comment.

**Comment by AndroidPoet** [comment]
> cmonfortep

Hi @cmonfortep i am bit busy with interviews will push code next week .

**Comment by cmonfortep** [comment]
Heads-up I won't be available next week, but someone from the team will be able to review it.

Same as I posted in the other PR, we can keep this PR open if we actively working on it, otherwise it's best if we close it until we have time again for it. Thanks

**Comment by AndroidPoet** [comment]
Sure! i will reopen it again we can close this as of now.

**Comment by malmstein** [comment]
@cmonfortep assigning to you for clarity
@AndroidPoet is this still active? Can it be closed?

**Pull request closed without merging**
