### PR TITLE
Add pixels

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/0/1208011850423576/f

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4902?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4902** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4902?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4897** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4897?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4872** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4872?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4824** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4824?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4780** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4780?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4752** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4752?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4748** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4663** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4663?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CrisBarreiro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by marcosholgado — APPROVED** [review]
LGTM. I'd like to find a way to move most of the logic from the DuckPlayerJsHelper into the duck player module but that's ok for now.

Also I'm not sure if this is the expected behaviour so just noting it here for you to check. The `duck-player_view-from_other` pixel is fired after clicking turn on duck player on the overlay, I don't think it should be fired though but not 100% sure.

**Comment by CrisBarreiro** [comment]
> LGTM. I'd like to find a way to move most of the logic from the DuckPlayerJsHelper into the duck player module but that's ok for now.
> 
> Also I'm not sure if this is the expected behaviour so just noting it here for you to check. The `duck-player_view-from_other` pixel is fired after clicking turn on duck player on the overlay, I don't think it should be fired though but not 100% sure.

@marcosholgado you're right. That pixel shouldn't be fired

on #1. There are a couple of reasons why I decided to keep it on the app module
* I think the fact we're using JS messages is an implementation detail on the browser, not Duck Player itsels
* We can't access BrowserTabViewModelcommands from Duck Player. However, we could introduce some "commands" in Duck Player and then map them to the actual ones in BrowserTabViewModel

No strong opinions though

**Comment by marcosholgado** [comment]
> > LGTM. I'd like to find a way to move most of the logic from the DuckPlayerJsHelper into the duck player module but that's ok for now.
> > Also I'm not sure if this is the expected behaviour so just noting it here for you to check. The `duck-player_view-from_other` pixel is fired after clicking turn on duck player on the overlay, I don't think it should be fired though but not 100% sure.
> 
> @marcosholgado you're right. That pixel shouldn't be fired
> 
> on #1. There are a couple of reasons why I decided to keep it on the app module
> 
> * I think the fact we're using JS messages is an implementation detail on the browser, not Duck Player itsels
> * We can't access BrowserTabViewModelcommands from Duck Player. However, we could introduce some "commands" in Duck Player and then map them to the actual ones in BrowserTabViewModel
> 
> No strong opinions though

Fair

**Comment by CrisBarreiro** [comment]
@marcosholgado the pixel was fired due to a regression in CSS. There's a new commit addressing it on the CSS branch

**Pull request closed without merging**
