### PR TITLE
Fix <br/> in app tracing protection waitlist (pl locales)

### PR DESCRIPTION
**Pull request by MedzikUser**
Task/Issue URL: 

### Description

image

before

### Steps to test this PR

- Join to App tracking protection in Polish app language

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

### CODE REVIEW

**Comment by xilusia** [comment]
segz

**Comment by MedzikUser** [comment]
waitlist*

**Comment by cmonfortep** [comment]
Thanks, @MedzikUser we are currently reviewing all our app strings to detect any issues (including wrong characters).

**Comment by xilusia** [comment]
sex

**Pull request closed without merging**
