### PR TITLE
Remove unused callbacks

### PR DESCRIPTION
**Pull request by karlenDimla**
Task/Issue URL: https://app.asana.com/0/488551667048375/1204088747317842/f

### Description
Remove onVpnStarting and onVpnStartFailed

### Steps to test this PR

N/A

### CODE REVIEW

**Comment by karlenDimla** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2894** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2894" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2894?utm_source=stack-comment).

**Comment by aitorvs** [comment]
Do we want to remove them? Even if empty now, they make sense

**Comment by HartOfALion22** [comment]
There's reason my Mother should be able to literally watch everything I'm
doing on my phone I'm 36 I never agreed to anything involving her

**Comment by HartOfALion22** [comment]
Absolutely has to be removed!!!

**Pull request closed without merging**
