### PR TITLE
Use latest tag to retrieve versionCode for nightly releases

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/1174433894299346/1208382292008137/f

### Steps to test this PR

_Nightly_
- [ ] ./gradlew getBuildVersionCode -PversionNameSuffix=-nightly
- [ ] Verify that versionCode increments (Previous code was 5, incrementing to 6)

_Production_
- [ ] ./gradlew getBuildVersionCode
- [ ] Verify that versionCode is 0

### CODE REVIEW

**Comment by malmstein** [comment]
* **#5056** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5056?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @malmstein and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by CDRussell — COMMENTED** [review]
I can see this working, in that it returns a build number than the last tag, but the build ends in a failure. Both of these end in a failure:
- `./gradlew getBuildVersionCode -PversionNameSuffix=-nightly`
- `./gradlew getBuildVersionCode`


The reason for the failure is that your changes aren't compatible with gradle configuration caching. I can workaround it by forcing disabling the config cache (e.g., `./gradlew getBuildVersionCode -PversionNameSuffix=-nightly -Dorg.gradle.configuration-cache=false`) but doesn't seem right that would be required.

Can you look into what's happening here, and if there's a better way of getting the job to finish successfully that doesn't require disabling the config cache with that param?

```
This is a nightly release, incrementing from previous release...
Last tag 5.215.0.12-nightly
 was a nightly release, incrementing from previous one...
Previous code was 12, incrementing to 13
13
FAILURE: Build failed with an exception.

* Where:
Script '/Users/craig/dev/source/ddg/Android/versioning.gradle' line: 37

* What went wrong:
Configuration cache problems found in this build.

4 problems were found storing the configuration cache, 2 of which seem unique.
- Script 'versioning.gradle': line 37: external process started 'git rev-list --tags --max-count=1'
  See https://docs.gradle.org/8.8/userguide/configuration_cache.html#config_cache:requirements:external_processes
- Script 'versioning.gradle': line 39: external process started 'git describe --tags 87492075b6ef4db8c015b000b64bb789c291dca2
'
  See https://docs.gradle.org/8.8/userguide/configuration_cache.html#config_cache:requirements:external_processes

See the complete report at file:///Users/craig/dev/source/ddg/Android/build/reports/configuration-cache/3ew6l1z4n7n4ky4aqqi9c1otr/1i7lwo9tqbqc92v4cmtarf0o4/configuration-cache-report.html
> Starting an external process 'git rev-list --tags --max-count=1' during configuration time is unsupported.
> Starting an external process 'git describe --tags 87492075b6ef4db8c015b000b64bb789c291dca2
  ' during configuration time is unsupported.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Comment by malmstein** [comment]
Interesting @CDRussell . I don’t have gradle configuration cache disabled and the build is not failing for me.

**Review by CDRussell — APPROVED** [review]

**Comment by malmstein** [comment]
Thanks @CDRussell ! Will add the flag in the release task.

**Pull request merged**
