### PR TITLE
Improve tab switcher ui

### PR DESCRIPTION
**Pull request by fgei**
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/361925093999567

**Description**:
 Improved tab switcher UI following latest iOS design on Zeplin

**Steps to test this PR**:
1. Create a tab and open the Tab Switcher
2. Confirm that the tab switcher UI has changed

###### Reviewer Checklist:
- [x] **Ensure the PR solves the problem**
- [x] **Review every line of code**
- [x] **Ensure the PR does no harm by testing the changes thoroughly**
- [x] **Get help if you're uncomfortable with any of the above!**
- [x] Determine if there are any quick wins that improve the implementation

###### PR DRI Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications (Database connections, Grafana stats, CPU)

### CODE REVIEW

**Comment by fgei** [comment]
@subsymbolic I don't think you reviewed/approved this yet
if you confirm that it's ok I'll merge

**Comment by subsymbolic** [comment]
Ahh actually hold off the merge, Francesco. I do still need to review this one, I'll comment when I'm done.

**Comment by fgei** [comment]
ok @subsymbolic, perfect timing I was just going to merge this :)

**Comment by subsymbolic** [comment]
Does pressing forget work for you on API 18? I'm seeing a crash.

**Comment by fgei** [comment]
ah yes, I just tested on kitkat and older, I can reproduce this but the Logcat is showing nothing related, I'll check it out now

**Comment by fgei** [comment]
@subsymbolic this should be fixed, couldn't test this on a real device but it's working on the emulator

**Comment by subsymbolic** [comment]
Look good! Feel free to merge

**Pull request merged**
