### PR TITLE
Fix ANR in DuckPlayerLocalFilesPath

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208851110314077/f 

### Steps to test this PR
Smoke test Duck Player

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
* **#5340** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5340?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5340?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `develop`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by CDRussell** [comment]
@CrisBarreiro, would it not make things easier to mark `isSimulatedYoutubeNoCookie` as a `suspend` function? 
- that’s the only thing I can see calling `duckPlayerLocalFilesPath.assetsPath()`
- `isSimulatedYoutubeNoCookie` is only ever called from coroutines anyway so there wouldn't be a large bubble-up effect of adding the `suspend` marker

if you did that, could ensure that `duckPlayerLocalFilesPath.assetsPath()` is called on the `io` dispatcher

**Comment by CrisBarreiro** [comment]
> @CrisBarreiro, would it make things easier to mark `isSimulatedYoutubeNoCookie` as a `suspend` function, instead of the changes in this PR?
> 
>     * that’s the only thing I can see calling `duckPlayerLocalFilesPath.assetsPath()`
> 
>     * `isSimulatedYoutubeNoCookie` is only ever called from coroutines anyway so there wouldn't be a large bubble-up effect of adding the `suspend` marker
> 
> 
> if you did that, could ensure that `duckPlayerLocalFilesPath.assetsPath()` is called on the `io` dispatcher

@CDRussell there's one usage that doesn't come from a suspend fun. However, since we're prefetching and caching the value of assetsPath, I don't think it's needed. Moreover, we removed all suspend functions in https://github.com/duckduckgo/Android/pull/5257/, which fixed the prior ANR, so I would prefer to try this out first, and not go back to suspend functions that ultimately will require a runBlocking

**Review by cmonfortep — APPROVED** [review]
LGTM :shipit:

**Review by joshliebe — APPROVED** [review]
Tested and works as expected ✅
This should fix the ANR, nicely done 👍

**Pull request merged**
