### PR TITLE
Re-add api 30 changes

### PR DESCRIPTION
**Pull request by marcosholgado**
Task/Issue URL: https://app.asana.com/0/414730916066338/1200094754307600
Tech Design URL: 
CC: 

**Description**:
This PR changes the target SDK to API 30

**Steps to test this PR**:

**Query permissions**:
1. Install the app and add the search widget
1. Click on the widget and try to search for one of the apps you have installed in your phone (not the stock ones)
1. The app should show up in the autocomplete results
1. Click on the app and make sure it opens correctly

**Download images**:
1. Search for any images in SERP
1. Long click in one of the images and press `Download Image`
1. The image should be saved correctly

**Download blobs**:
1. Go to `https://eligrey.com/demos/FileSaver.js`
1. Try to save the some files from the site
1. All the files should be saved correctly

**Download files**:
1. Go to `https://github.com/duckduckgo/Android/releases`
1. Try to download one of our APKs
1. File should be saved correctly
1. Go to `https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/`
1. Click on any PDF.
1. If you select to not open with another app the document should be correctly saved.
1. If you select to open with another app the document should be opened in that app.

**Favicons and preview images**
1. Go to `github.com`
1. Go to the tab swticher
1. Make sure you can see the favicon and the preview image.
1. Add the site to your bookmarks
1. Go to bookmarks
1. Make sure the favicon shows up correctly

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by CDRussell — CHANGES_REQUESTED** [review]
As per conversation [here](https://app.asana.com/0/414730916066338/1200094754307600/f), I don't think this is the right path forward. 

Leaving this comment here so the PR doesn't get merged until we resolve that conversation.

**Comment by CDRussell** [comment]
## Test results - WIP 🚧

#### Pixel 2, Android 11

Scenario | Test results
---|:---:
Query permissions | ✅ 
Download images | ✅
Download blobs | ✅
Download files | ✅ 
Favicons and preview images | ✅


#### Samsung A5, Android 6.0.1 

Scenario | Test results
---|:---:
Query permissions | ✅
Download images | ✅
Download blobs | ✅
Download files | ✅
Favicons and preview images | ✅


#### Samsung A20e, Android 11

Scenario | Test results
---|:---:
Query permissions | XXXX
Download images | XXXX
Download blobs | XXXX
Download files | XXXX
Favicons and preview images | XXXX

#### Samsung S6, Android 7.0

Scenario | Test results
---|:---:
Query permissions | XXXX
Download images | XXXX
Download blobs | XXXX
Download files | XXXX
Favicons and preview images | XXXX


#### Xiaomi Mi 10, Android ❓ 

Scenario | Test results
---|:---:
Query permissions | XXXX
Download images | XXXX
Download blobs | XXXX
Download files | XXXX
Favicons and preview images | XXXX

**Review by CDRussell — APPROVED** [review]
The failure case happens today in production too so we haven't made that worse. Would recommend deferring that issue for now and carrying on

**Comment by marcosholgado** [comment]
Merged as a hotfix (5.97.0), thanks @CDRussell

**Pull request closed without merging**
