### PR TITLE
Removed the code for AppTP Promo experiment.

### PR DESCRIPTION
**Pull request by anikiki**
Task/Issue URL: https://app.asana.com/0/0/1204431384408588/f

### Description
Removed the code for AppTP Promo experiment. See the previous PR which added the experiment -> https://github.com/duckduckgo/Android/pull/3080

### Steps to test this PR

- [x] Install from this branch.
- [x] Go through onboarding and see there's nothing unusual.

### NO UI changes

### CODE REVIEW

**Comment by anikiki** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3337** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3337" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3337?utm_source=stack-comment).

**Comment by CDRussell** [comment]
One thought while I test out this branch and the code: is it possible that someone on a previous version in the experiment would have an unopened notification, and then upgrade to this version and tap the notification... if that happened, would anything bad happen?

**Review by CDRussell — APPROVED** [review]
LGTM.

**Comment by anikiki** [comment]
> One thought while I test out this branch and the code: is this scenario possible
> 
>     1. someone was on a previous version and in the experiment
> 
>     2. they had an unopened notification
> 
>     3. they upgrade to this version
> 
>     4. they tap the notification
> 
> 
> if that happened, would anything bad happen?

It is a valid scenario where tapping on the notification won't do anything (worst case crash?). Given that the experiment was disabled a couple of weeks ago and the engagement with the notification was not high I don't think it makes sense to add additional protections against this.

**Review by nalcalag — APPROVED** [review]
You handled all "conflicts" with the new notification experiment very well.
You are the best @anikiki ! 🔥

**Pull request merged**
