### PR TITLE
Set voice search feature to disabled by default

### PR DESCRIPTION
**Pull request by CrisBarreiro**
Task/Issue URL: https://app.asana.com/0/0/1205628562025903/f 

### Description
Set voice search feature to disabled by default, except for Pixel 6 and Pixel 6 Pro devices where it had previously been used

### Steps to test this PR

_Default disabled_
- [x] Perform a clean install and check voice search icon isn't shown

_Disabled if user had never used voice search before_
- [ ] Perform a clean install of a develop build on a Pixel 6 or 6 Pro, click on the mic icon, and decline the first dialog shown
- [ ] Now install a version from this PR, and check voice search icon is not shown 

_Enabled if user had previously accepted voice search permissions rationale_
- [ ] Perform a clean install of a develop build on a Pixel 6 or 6 Pro, click on the mic icon, and accept the first dialog shown
- [ ] Now install a version from this PR, and check voice search icon is shown 

Alternatively, if you don't have a Pixel 6 or 6 Pro, you can edit `RealVoiceSearchAvailability#allowList` and add your device name there

### UI changes
No UI changes

### CODE REVIEW

**Comment by CrisBarreiro** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3477** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3477" target="_blank">Graphite</a> 
    * **PR #3583** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3583" target="_blank">Graphite</a> 
      * **PR #3585** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3585" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3587" target="_blank">Graphite</a> 
          * **PR #3607** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3607" target="_blank">Graphite</a> 
            * **PR #3608** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3608" target="_blank">Graphite</a>  👈
    * **PR #3574** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3574" target="_blank">Graphite</a> 
    * **PR #3489** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3489" target="_blank">Graphite</a> 
      * **PR #3516** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3516" target="_blank">Graphite</a> 
      * **PR #3491** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3491" target="_blank">Graphite</a> 
      * **PR #3490** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3490" target="_blank">Graphite</a> 
        * **PR #3528** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3528" target="_blank">Graphite</a> 
          * **PR #3541** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3541" target="_blank">Graphite</a> 
            * **PR #3564** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3564" target="_blank">Graphite</a> 
              * **PR #3567** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3567" target="_blank">Graphite</a> 
            * **PR #3550** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3550" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3608?utm_source=stack-comment).

**Comment by CrisBarreiro** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3477** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3477" target="_blank">Graphite</a> 
    * **PR #3583** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3583" target="_blank">Graphite</a> 
      * **PR #3585** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3585" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3587" target="_blank">Graphite</a> 
          * **PR #3607** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3607" target="_blank">Graphite</a> 
            * **PR #3608** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3608" target="_blank">Graphite</a>  👈
    * **PR #3574** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3574" target="_blank">Graphite</a> 
    * **PR #3489** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3489" target="_blank">Graphite</a> 
      * **PR #3516** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3516" target="_blank">Graphite</a> 
      * **PR #3491** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3491" target="_blank">Graphite</a> 
      * **PR #3490** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3490" target="_blank">Graphite</a> 
        * **PR #3528** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3528" target="_blank">Graphite</a> 
          * **PR #3541** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3541" target="_blank">Graphite</a> 
            * **PR #3564** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3564" target="_blank">Graphite</a> 
              * **PR #3567** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3567" target="_blank">Graphite</a> 
            * **PR #3550** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3550" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3608?utm_source=stack-comment).

**Comment by CrisBarreiro** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3477** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3477" target="_blank">Graphite</a> 
    * **PR #3583** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3583" target="_blank">Graphite</a> 
      * **PR #3585** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3585" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3587" target="_blank">Graphite</a> 
          * **PR #3607** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3607" target="_blank">Graphite</a> 
            * **PR #3608** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3608" target="_blank">Graphite</a>  👈
    * **PR #3574** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3574" target="_blank">Graphite</a> 
    * **PR #3489** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3489" target="_blank">Graphite</a> 
      * **PR #3516** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3516" target="_blank">Graphite</a> 
      * **PR #3491** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3491" target="_blank">Graphite</a> 
      * **PR #3490** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3490" target="_blank">Graphite</a> 
        * **PR #3528** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3528" target="_blank">Graphite</a> 
          * **PR #3541** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3541" target="_blank">Graphite</a> 
            * **PR #3564** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3564" target="_blank">Graphite</a> 
              * **PR #3567** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3567" target="_blank">Graphite</a> 
            * **PR #3550** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3550" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3608?utm_source=stack-comment).

**Review by anikiki — APPROVED** [review]
Looks good and works as expected! :tada:

**Pull request merged**
