### PR TITLE
Moving out of TrackersAnimatorHelper any coroutine ownership

### PR DESCRIPTION
**Pull request by cmonfortep**
Task/Issue URL: https://app.asana.com/0/414730916066338/1161183674646971/f
Tech Design URL: 
CC: 

**Description**:
* animation job is now owned by the class using this helper
* corutineScope is owned by a fragment, which scope can be controlled by its lifecycle

**Steps to test this PR**:
1. Hardcode a variant that enables concept test
2. Navigate to any site (better if it's a site that contains trackers)
3. Ensure scan animation still works: Showing scanning animation when page is loading, and trackers animation when page is loaded

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by cmonfortep** [comment]
@marcosholgado I think you are the most convenient reviewer for this PR.

**Comment by malmstein** [comment]
@cmonfortep should this be closed until you have time to work on it again?

**Comment by cmonfortep** [comment]
I think next week I will be able to dedicate some time to this PR. Thanks for the reminder.

**Comment by cmonfortep** [comment]
Actually, I'm going to close this as https://github.com/duckduckgo/Android/pull/715 will remove the coroutineScope inside that class.

**Pull request closed without merging**
