### PR TITLE
Omnibar

### PR DESCRIPTION
**Pull request by fgei**
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/364465928695402

**Description**: Update the Omnibar UI to latest iOS build and latest Zeplin iOS design file

**Steps to test this PR**:
1. Open the app and see that the Omnibus UI changed.
2. Confirm that the overflow button still open the main menu.
3. Confirm that when pressing on the Omnibar, the back arrow become visible and when pressed bring the Omnibar to the previous state.
4. Confirm that when pressing on the Omnibar the "cancel text" button become visible only after start typing and goes aways after removing all the letters, and when pressing the button correctly delete all the letters. 

###### Reviewer Checklist:
- [x] **Ensure the PR solves the problem**
- [x] **Review every line of code**
- [x] **Ensure the PR does no harm by testing the changes thoroughly**
- [x] **Get help if you're uncomfortable with any of the above!**
- [x] Determine if there are any quick wins that improve the implementation

###### PR DRI Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications (Database connections, Grafana stats, CPU)

### CODE REVIEW

**Comment by subsymbolic** [comment]
Great work @fgei. Only one request - can you update the light on light text and status bar icons to black so that they are legible? You don't need to fully theme the affected screens just do what needs to be done to ensure that the user is never given a lesser experience from a new PR.

**Comment by fgei** [comment]
@subsymbolic should be done now!

**Comment by subsymbolic** [comment]
Looks good, although the status bar is still light on light. Feel free to merge once you've fixed that.

**Comment by fgei** [comment]
yep @subsymbolic sorry, I forgot that "windowLightStatusBar" is only available from API 23 but the status bar is already tinted from API 21. in those case we still get light text on light background.

I set to tint the status bar background only from API 23, and leave the black status bar before that

**Pull request merged**
