### PR TITLE
Documentation and tests

### PR DESCRIPTION
**Pull request by nalcalag**
Task/Issue URL: 

### Description
Added few tests and documentation for site permissions API

### CODE REVIEW

**Comment by nalcalag** [comment]
Current dependencies on/for this PR:
* feature/noelia/site_permissions_launcher
  * **PR #2165** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2165" target="_blank">Graphite</a> 
    * **PR #2182** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2182" target="_blank">Graphite</a> 
      * **PR #2295** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2295" target="_blank">Graphite</a>  👈
      * **PR #2265** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2265" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2295?utm_source=stack-comment).

**Comment by nalcalag** [comment]
Current dependencies on/for this PR:
* feature/noelia/site_permissions_launcher
  * **PR #2165** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2165" target="_blank">Graphite</a> 
    * **PR #2182** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2182" target="_blank">Graphite</a> 
      * **PR #2295** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2295" target="_blank">Graphite</a>  👈
      * **PR #2265** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2265" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2295?utm_source=stack-comment).

**Comment by cmonfortep** [comment]
Same as in https://github.com/duckduckgo/Android/pull/2296, I think something went wrong when aligning between branches. Files changed in this PR contain changes from initial PRs. Could you double check this? Thanks!

**Review by cmonfortep — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
