### PR TITLE
Intentfix

### PR DESCRIPTION
**Pull request by wseemann**
Task/Issue URL: Android: Protect app from crashing due to unsafe input from 3rd parties #953
Tech Design URL: N/A
CC: N/A

Android: Protect app from crashing due to unsafe input from 3rd parties.

**Steps to test this PR**:
1. Send invalid intent to app, verify the app does not crash.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by cmonfortep — CHANGES_REQUESTED** [review]
Thanks for submitting this PR.

This fixes the crash report we shared in https://github.com/duckduckgo/Android/issues/953, but it still crashes when accessing the intent at:
```
at com.duckduckgo.app.global.IntentExtensionKt.getIntentText(IntentExtension.kt:23)
        at com.duckduckgo.app.fire.DataClearerForegroundAppRestartPixel.registerIntent(DataClearerForegroundAppRestartPixel.kt:62)
        at com.duckduckgo.app.browser.BrowserActivity.onNewIntent(BrowserActivity.kt:132)
```

About the proposed solution:

It's ok to use, on every intent access, the new proposed class `ContextUtils`, but I would like to suggest also creating a method that sanitizes the intent (like Chrome does). That method could be used to reduce verbosity when accessing multiple times the same `Intent`.

The method logic will be:
1. try to get extra (`intent.extras`) from an intent (it will crash here)
2. If exception captured, return same intent without extras (so it will not crash anymore)
3. return sanitized intent

**Comment by cmonfortep** [comment]
@wseemann are you open to continue working on this PR? Let me know if you are still interested or I can open it for new contributors. Thanks!

**Comment by wseemann** [comment]
@cmonfortep I'm working on the revisions. Sorry for the delay, it's Monday so I was busy catching up on work at my full time job. I will try and get the revisions in within the next day or so.

**Comment by cmonfortep** [comment]
No problem, take as time as you need here. I will be on the other side for anything you need here 👍

**Comment by cmonfortep** [comment]
@wseemann Thanks so much for contributing, however, we need to decline this PR (as it is now) since we noticed the code comes from another repository and we only accept unique contributions.

**Comment by wseemann** [comment]
@cmonfortep No problem. I figured an open source project would want to leverage code that already works from another quality open source project rather then reinvent the wheel. After all, that's kind of the point of making things open source.

**Pull request closed without merging**
