### PR TITLE
Android: Opening link after inactivity data clear time fails to load page.

### PR DESCRIPTION
**Pull request by cmonfortep**
Task/Issue URL: 
Tech Design URL: 
CC: 

**Description**:

**Steps to test this PR**:
1. 
1. 

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by cmonfortep** [comment]
@CDRussell would you mind to review this draft to validate if the approach is correct?

**Comment by CDRussell** [comment]
@cmonfortep, happy to. would need to be next week though if that works for you

**Comment by cmonfortep** [comment]
All good, whenever you have time for it.

**Comment by cmonfortep** [comment]
We will try to analyze first what's the impact of this bug and how many possible launches are affected. After that, we will prioritize and look for a new strategy.

**Pull request closed without merging**
