### PR TITLE
ADS: Remove extra Dialog test

### PR DESCRIPTION
**Pull request by malmstein**
Task/Issue URL: https://app.asana.com/0/414730916066338/1205716607749330/f 

### Description
Fixes Maestro test issue 

### Steps to test this PR
https://github.com/duckduckgo/Android/actions/runs/6535124479/job/17743840123

### CODE REVIEW

**Comment by malmstein** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3692** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3692" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3692?utm_source=stack-comment).

**Comment by malmstein** [comment]
@nalcalag this is ready for review

**Review by marcosholgado — APPROVED** [review]
LGTM. This is not really adding any scroll btw, just removing an assertion that's not done anymore. Not sure if this is desired.

**Comment by nalcalag** [comment]
> LGTM. This is not really adding any scroll btw, just removing an assertion that's not done anymore. Not sure if this is desired.

+1

**Comment by malmstein** [comment]
Thanks both!

**Pull request merged**
